// Code generated by gen-api from OpenAPI spec; DO NOT EDIT.

package apiv3

import (
	"context"
	"fmt"
	"net/url"
	"strconv"

	"github.com/toppynl/clickup-cli/internal/api"
	clickupv3 "github.com/toppynl/clickup-cli/api/clickupv3"
)

// Ensure imports are used.
var _ = fmt.Sprintf
var _ = url.Values{}
var _ = strconv.Itoa

// CreateChatChannel — Create a Channel
// POST /workspaces/%s/chat/channels
func CreateChatChannel(ctx context.Context, client *api.Client, workspaceId string, req *clickupv3.ChatCreateChatChannel) error {
	path := fmt.Sprintf("workspaces/%s/chat/channels", workspaceId)
	return do(ctx, client, "POST", path, req, nil)
}

// CreateChatMessage — Send a message
// POST /workspaces/%s/chat/channels/%s/messages
func CreateChatMessage(ctx context.Context, client *api.Client, workspaceId string, channelId string, req *clickupv3.CommentCreateChatMessage) (*clickupv3.CommentCreateChatMessageResponse, error) {
	var resp clickupv3.CommentCreateChatMessageResponse
	path := fmt.Sprintf("workspaces/%s/chat/channels/%s/messages", workspaceId, channelId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateChatReaction — Create a message reaction
// POST /workspaces/%s/chat/messages/%s/reactions
func CreateChatReaction(ctx context.Context, client *api.Client, workspaceId string, messageId string, req *clickupv3.CommentCreateChatReaction) (*clickupv3.ChatReaction, error) {
	var resp clickupv3.ChatReaction
	path := fmt.Sprintf("workspaces/%s/chat/messages/%s/reactions", workspaceId, messageId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateDirectMessageChatChannel — Create a Direct Message
// POST /workspaces/%s/chat/channels/direct_message
func CreateDirectMessageChatChannel(ctx context.Context, client *api.Client, workspaceId string, req *clickupv3.ChatCreateDirectMessageChatChannel) error {
	path := fmt.Sprintf("workspaces/%s/chat/channels/direct_message", workspaceId)
	return do(ctx, client, "POST", path, req, nil)
}

// CreateDocPublic — Create a Doc
// POST /workspaces/%s/docs
func CreateDocPublic(ctx context.Context, client *api.Client, workspaceId string, req *clickupv3.PublicDocsCreateDocOptionsDto) (*clickupv3.PublicDocsDocDto, error) {
	var resp clickupv3.PublicDocsDocDto
	path := fmt.Sprintf("workspaces/%s/docs", workspaceId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateLocationChatChannel — Create a Channel on a Space, Folder, or List
// POST /workspaces/%s/chat/channels/location
func CreateLocationChatChannel(ctx context.Context, client *api.Client, workspaceId string, req *clickupv3.ChatCreateLocationChatChannel) error {
	path := fmt.Sprintf("workspaces/%s/chat/channels/location", workspaceId)
	return do(ctx, client, "POST", path, req, nil)
}

// CreatePagePublic — Create a Page
// POST /workspaces/%s/docs/%s/pages
func CreatePagePublic(ctx context.Context, client *api.Client, workspaceId string, docId string, req *clickupv3.PublicDocsPublicCreatePageOptionsDto) (*clickupv3.PublicDocsPageV3Dto, error) {
	var resp clickupv3.PublicDocsPageV3Dto
	path := fmt.Sprintf("workspaces/%s/docs/%s/pages", workspaceId, docId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateReplyMessage — Create a reply message
// POST /workspaces/%s/chat/messages/%s/replies
func CreateReplyMessage(ctx context.Context, client *api.Client, workspaceId string, messageId string, req *clickupv3.CommentCreateChatMessage) (*clickupv3.CommentCreateReplyMessageResponse, error) {
	var resp clickupv3.CommentCreateReplyMessageResponse
	path := fmt.Sprintf("workspaces/%s/chat/messages/%s/replies", workspaceId, messageId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteChatChannel — Delete a Channel
// DELETE /workspaces/%s/chat/channels/%s
func DeleteChatChannel(ctx context.Context, client *api.Client, workspaceId string, channelId string) error {
	path := fmt.Sprintf("workspaces/%s/chat/channels/%s", workspaceId, channelId)
	return do(ctx, client, "DELETE", path, nil, nil)
}

// DeleteChatMessage — Delete a message
// DELETE /workspaces/%s/chat/messages/%s
func DeleteChatMessage(ctx context.Context, client *api.Client, workspaceId string, messageId string) error {
	path := fmt.Sprintf("workspaces/%s/chat/messages/%s", workspaceId, messageId)
	return do(ctx, client, "DELETE", path, nil, nil)
}

// DeleteChatReaction — Delete a message reaction
// DELETE /workspaces/%s/chat/messages/%s/reactions/%s
func DeleteChatReaction(ctx context.Context, client *api.Client, workspaceId string, messageId string, reaction string) error {
	path := fmt.Sprintf("workspaces/%s/chat/messages/%s/reactions/%s", workspaceId, messageId, reaction)
	return do(ctx, client, "DELETE", path, nil, nil)
}

// EditPagePublic — Edit a Page
// PUT /workspaces/%s/docs/%s/pages/%s
func EditPagePublic(ctx context.Context, client *api.Client, workspaceId string, docId string, pageId string, req *clickupv3.PublicDocsPublicEditPageOptionsDto) error {
	path := fmt.Sprintf("workspaces/%s/docs/%s/pages/%s", workspaceId, docId, pageId)
	return do(ctx, client, "PUT", path, req, nil)
}

// GetChatChannelParams holds optional query parameters for GetChatChannel.
type GetChatChannelParams struct {
	DescriptionFormat string `url:"description_format,omitempty"`
}

func (p GetChatChannelParams) encode() string {
	q := url.Values{}
	if p.DescriptionFormat != "" { q.Set("description_format", p.DescriptionFormat) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetChatChannel — Retrieve a Channel
// GET /workspaces/%s/chat/channels/%s
func GetChatChannel(ctx context.Context, client *api.Client, workspaceId string, channelId string, opts ...GetChatChannelParams) error {
	path := fmt.Sprintf("workspaces/%s/chat/channels/%s", workspaceId, channelId)
	if len(opts) > 0 { path += opts[0].encode() }
	return do(ctx, client, "GET", path, nil, nil)
}

// GetChatChannelFollowersParams holds optional query parameters for GetChatChannelFollowers.
type GetChatChannelFollowersParams struct {
	Cursor string `url:"cursor,omitempty"`
	Limit int `url:"limit,omitempty"`
}

func (p GetChatChannelFollowersParams) encode() string {
	q := url.Values{}
	if p.Cursor != "" { q.Set("cursor", p.Cursor) }
	if p.Limit != 0 { q.Set("limit", strconv.Itoa(p.Limit)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetChatChannelFollowers — Retrieve Channel followers
// GET /workspaces/%s/chat/channels/%s/followers
func GetChatChannelFollowers(ctx context.Context, client *api.Client, workspaceId string, channelId string, opts ...GetChatChannelFollowersParams) error {
	path := fmt.Sprintf("workspaces/%s/chat/channels/%s/followers", workspaceId, channelId)
	if len(opts) > 0 { path += opts[0].encode() }
	return do(ctx, client, "GET", path, nil, nil)
}

// GetChatChannelMembersParams holds optional query parameters for GetChatChannelMembers.
type GetChatChannelMembersParams struct {
	Cursor string `url:"cursor,omitempty"`
	Limit int `url:"limit,omitempty"`
}

func (p GetChatChannelMembersParams) encode() string {
	q := url.Values{}
	if p.Cursor != "" { q.Set("cursor", p.Cursor) }
	if p.Limit != 0 { q.Set("limit", strconv.Itoa(p.Limit)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetChatChannelMembers — Retrieve Channel members
// GET /workspaces/%s/chat/channels/%s/members
func GetChatChannelMembers(ctx context.Context, client *api.Client, workspaceId string, channelId string, opts ...GetChatChannelMembersParams) error {
	path := fmt.Sprintf("workspaces/%s/chat/channels/%s/members", workspaceId, channelId)
	if len(opts) > 0 { path += opts[0].encode() }
	return do(ctx, client, "GET", path, nil, nil)
}

// GetChatChannelsParams holds optional query parameters for GetChatChannels.
type GetChatChannelsParams struct {
	DescriptionFormat string `url:"description_format,omitempty"`
	Cursor string `url:"cursor,omitempty"`
	Limit int `url:"limit,omitempty"`
	IsFollower bool `url:"is_follower,omitempty"`
	IncludeClosed bool `url:"include_closed,omitempty"`
	WithMessageSince float64 `url:"with_message_since,omitempty"`
	ChannelTypes string `url:"channel_types,omitempty"`
}

func (p GetChatChannelsParams) encode() string {
	q := url.Values{}
	if p.DescriptionFormat != "" { q.Set("description_format", p.DescriptionFormat) }
	if p.Cursor != "" { q.Set("cursor", p.Cursor) }
	if p.Limit != 0 { q.Set("limit", strconv.Itoa(p.Limit)) }
	if p.IsFollower { q.Set("is_follower", "true") }
	if p.IncludeClosed { q.Set("include_closed", "true") }
	if p.WithMessageSince != 0 { q.Set("with_message_since", fmt.Sprintf("%g", p.WithMessageSince)) }
	if p.ChannelTypes != "" { q.Set("channel_types", p.ChannelTypes) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetChatChannels — Retrieve Channels
// GET /workspaces/%s/chat/channels
func GetChatChannels(ctx context.Context, client *api.Client, workspaceId string, opts ...GetChatChannelsParams) error {
	path := fmt.Sprintf("workspaces/%s/chat/channels", workspaceId)
	if len(opts) > 0 { path += opts[0].encode() }
	return do(ctx, client, "GET", path, nil, nil)
}

// GetChatMessageReactionsParams holds optional query parameters for GetChatMessageReactions.
type GetChatMessageReactionsParams struct {
	Cursor string `url:"cursor,omitempty"`
	Limit int `url:"limit,omitempty"`
}

func (p GetChatMessageReactionsParams) encode() string {
	q := url.Values{}
	if p.Cursor != "" { q.Set("cursor", p.Cursor) }
	if p.Limit != 0 { q.Set("limit", strconv.Itoa(p.Limit)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetChatMessageReactions — Retrieve message reactions
// GET /workspaces/%s/chat/messages/%s/reactions
func GetChatMessageReactions(ctx context.Context, client *api.Client, workspaceId string, messageId string, opts ...GetChatMessageReactionsParams) error {
	path := fmt.Sprintf("workspaces/%s/chat/messages/%s/reactions", workspaceId, messageId)
	if len(opts) > 0 { path += opts[0].encode() }
	return do(ctx, client, "GET", path, nil, nil)
}

// GetChatMessageRepliesParams holds optional query parameters for GetChatMessageReplies.
type GetChatMessageRepliesParams struct {
	Cursor string `url:"cursor,omitempty"`
	Limit int `url:"limit,omitempty"`
	ContentFormat string `url:"content_format,omitempty"`
}

func (p GetChatMessageRepliesParams) encode() string {
	q := url.Values{}
	if p.Cursor != "" { q.Set("cursor", p.Cursor) }
	if p.Limit != 0 { q.Set("limit", strconv.Itoa(p.Limit)) }
	if p.ContentFormat != "" { q.Set("content_format", p.ContentFormat) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetChatMessageReplies — Retrieve message replies
// GET /workspaces/%s/chat/messages/%s/replies
func GetChatMessageReplies(ctx context.Context, client *api.Client, workspaceId string, messageId string, opts ...GetChatMessageRepliesParams) error {
	path := fmt.Sprintf("workspaces/%s/chat/messages/%s/replies", workspaceId, messageId)
	if len(opts) > 0 { path += opts[0].encode() }
	return do(ctx, client, "GET", path, nil, nil)
}

// GetChatMessageTaggedUsersParams holds optional query parameters for GetChatMessageTaggedUsers.
type GetChatMessageTaggedUsersParams struct {
	Cursor string `url:"cursor,omitempty"`
	Limit int `url:"limit,omitempty"`
}

func (p GetChatMessageTaggedUsersParams) encode() string {
	q := url.Values{}
	if p.Cursor != "" { q.Set("cursor", p.Cursor) }
	if p.Limit != 0 { q.Set("limit", strconv.Itoa(p.Limit)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetChatMessageTaggedUsers — Retrieve message tagged users
// GET /workspaces/%s/chat/messages/%s/tagged_users
func GetChatMessageTaggedUsers(ctx context.Context, client *api.Client, workspaceId string, messageId string, opts ...GetChatMessageTaggedUsersParams) error {
	path := fmt.Sprintf("workspaces/%s/chat/messages/%s/tagged_users", workspaceId, messageId)
	if len(opts) > 0 { path += opts[0].encode() }
	return do(ctx, client, "GET", path, nil, nil)
}

// GetChatMessagesParams holds optional query parameters for GetChatMessages.
type GetChatMessagesParams struct {
	Cursor string `url:"cursor,omitempty"`
	Limit int `url:"limit,omitempty"`
	ContentFormat string `url:"content_format,omitempty"`
}

func (p GetChatMessagesParams) encode() string {
	q := url.Values{}
	if p.Cursor != "" { q.Set("cursor", p.Cursor) }
	if p.Limit != 0 { q.Set("limit", strconv.Itoa(p.Limit)) }
	if p.ContentFormat != "" { q.Set("content_format", p.ContentFormat) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetChatMessages — Retrieve Channel messages
// GET /workspaces/%s/chat/channels/%s/messages
func GetChatMessages(ctx context.Context, client *api.Client, workspaceId string, channelId string, opts ...GetChatMessagesParams) error {
	path := fmt.Sprintf("workspaces/%s/chat/channels/%s/messages", workspaceId, channelId)
	if len(opts) > 0 { path += opts[0].encode() }
	return do(ctx, client, "GET", path, nil, nil)
}

// GetDocPageListingPublicParams holds optional query parameters for GetDocPageListingPublic.
type GetDocPageListingPublicParams struct {
	MaxPageDepth float64 `url:"max_page_depth,omitempty"`
}

func (p GetDocPageListingPublicParams) encode() string {
	q := url.Values{}
	if p.MaxPageDepth != 0 { q.Set("max_page_depth", fmt.Sprintf("%g", p.MaxPageDepth)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetDocPageListingPublic — Fetch PageListing for a Doc
// GET /workspaces/%s/docs/%s/page_listing
func GetDocPageListingPublic(ctx context.Context, client *api.Client, workspaceId string, docId string, opts ...GetDocPageListingPublicParams) (*clickupv3.PublicDocsGetDocPageListingPublic200Response, error) {
	var resp clickupv3.PublicDocsGetDocPageListingPublic200Response
	path := fmt.Sprintf("workspaces/%s/docs/%s/page_listing", workspaceId, docId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetDocPagesPublicParams holds optional query parameters for GetDocPagesPublic.
type GetDocPagesPublicParams struct {
	MaxPageDepth float64 `url:"max_page_depth,omitempty"`
	ContentFormat string `url:"content_format,omitempty"`
}

func (p GetDocPagesPublicParams) encode() string {
	q := url.Values{}
	if p.MaxPageDepth != 0 { q.Set("max_page_depth", fmt.Sprintf("%g", p.MaxPageDepth)) }
	if p.ContentFormat != "" { q.Set("content_format", p.ContentFormat) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetDocPagesPublic — Fetch Pages belonging to a Doc
// GET /workspaces/%s/docs/%s/pages
func GetDocPagesPublic(ctx context.Context, client *api.Client, workspaceId string, docId string, opts ...GetDocPagesPublicParams) (*clickupv3.PublicDocsGetDocPagesPublic200Response, error) {
	var resp clickupv3.PublicDocsGetDocPagesPublic200Response
	path := fmt.Sprintf("workspaces/%s/docs/%s/pages", workspaceId, docId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetDocPublic — Fetch a Doc
// GET /workspaces/%s/docs/%s
func GetDocPublic(ctx context.Context, client *api.Client, workspaceId string, docId string) (*clickupv3.PublicDocsDocDto, error) {
	var resp clickupv3.PublicDocsDocDto
	path := fmt.Sprintf("workspaces/%s/docs/%s", workspaceId, docId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetPagePublicParams holds optional query parameters for GetPagePublic.
type GetPagePublicParams struct {
	ContentFormat string `url:"content_format,omitempty"`
}

func (p GetPagePublicParams) encode() string {
	q := url.Values{}
	if p.ContentFormat != "" { q.Set("content_format", p.ContentFormat) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetPagePublic — Get page
// GET /workspaces/%s/docs/%s/pages/%s
func GetPagePublic(ctx context.Context, client *api.Client, workspaceId string, docId string, pageId string, opts ...GetPagePublicParams) (*clickupv3.PublicDocsPageV3Dto, error) {
	var resp clickupv3.PublicDocsPageV3Dto
	path := fmt.Sprintf("workspaces/%s/docs/%s/pages/%s", workspaceId, docId, pageId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetParentEntityAttachmentsParams holds optional query parameters for GetParentEntityAttachments.
type GetParentEntityAttachmentsParams struct {
	Cursor string `url:"cursor,omitempty"`
	Limit int `url:"limit,omitempty"`
}

func (p GetParentEntityAttachmentsParams) encode() string {
	q := url.Values{}
	if p.Cursor != "" { q.Set("cursor", p.Cursor) }
	if p.Limit != 0 { q.Set("limit", strconv.Itoa(p.Limit)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetParentEntityAttachments — Get Attachments
// GET /workspaces/%s/%s/%s/attachments
func GetParentEntityAttachments(ctx context.Context, client *api.Client, workspaceId string, entityType string, entityId string, opts ...GetParentEntityAttachmentsParams) error {
	path := fmt.Sprintf("workspaces/%s/%s/%s/attachments", workspaceId, entityType, entityId)
	if len(opts) > 0 { path += opts[0].encode() }
	return do(ctx, client, "GET", path, nil, nil)
}

// GetSubtypes — Get Post Subtype IDs
// GET /workspaces/%s/comments/types/%s/subtypes
func GetSubtypes(ctx context.Context, client *api.Client, workspaceId string, commentType string) error {
	path := fmt.Sprintf("workspaces/%s/comments/types/%s/subtypes", workspaceId, commentType)
	return do(ctx, client, "GET", path, nil, nil)
}

// MoveTask — Move a task to a new List
// PUT /workspaces/%s/tasks/%s/home_list/%s
func MoveTask(ctx context.Context, client *api.Client, workspaceId string, taskId string, listId string, req *clickupv3.TaskMoveTaskBodyParamsDto) error {
	path := fmt.Sprintf("workspaces/%s/tasks/%s/home_list/%s", workspaceId, taskId, listId)
	return do(ctx, client, "PUT", path, req, nil)
}

// PatchChatMessage — Update a message
// PATCH /workspaces/%s/chat/messages/%s
func PatchChatMessage(ctx context.Context, client *api.Client, workspaceId string, messageId string, req *clickupv3.CommentPatchChatMessage) (*clickupv3.CommentPatchChatMessageResponse, error) {
	var resp clickupv3.CommentPatchChatMessageResponse
	path := fmt.Sprintf("workspaces/%s/chat/messages/%s", workspaceId, messageId)
	if err := do(ctx, client, "PATCH", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// QueryAuditLog — Create Workspace-level audit logs
// POST /workspaces/%s/auditlogs
func QueryAuditLog(ctx context.Context, client *api.Client, workspaceId string, req *clickupv3.AutoAuditlogAuditLogQueryRequest) error {
	path := fmt.Sprintf("workspaces/%s/auditlogs", workspaceId)
	return do(ctx, client, "POST", path, req, nil)
}

// SearchDocsPublicParams holds optional query parameters for SearchDocsPublic.
type SearchDocsPublicParams struct {
	Id string `url:"id,omitempty"`
	Creator float64 `url:"creator,omitempty"`
	Deleted bool `url:"deleted,omitempty"`
	Archived bool `url:"archived,omitempty"`
	ParentId string `url:"parent_id,omitempty"`
	ParentType string `url:"parent_type,omitempty"`
	Limit float64 `url:"limit,omitempty"`
	Cursor string `url:"cursor,omitempty"`
	NextCursor string `url:"next_cursor,omitempty"`
}

func (p SearchDocsPublicParams) encode() string {
	q := url.Values{}
	if p.Id != "" { q.Set("id", p.Id) }
	if p.Creator != 0 { q.Set("creator", fmt.Sprintf("%g", p.Creator)) }
	if p.Deleted { q.Set("deleted", "true") }
	if p.Archived { q.Set("archived", "true") }
	if p.ParentId != "" { q.Set("parent_id", p.ParentId) }
	if p.ParentType != "" { q.Set("parent_type", p.ParentType) }
	if p.Limit != 0 { q.Set("limit", fmt.Sprintf("%g", p.Limit)) }
	if p.Cursor != "" { q.Set("cursor", p.Cursor) }
	if p.NextCursor != "" { q.Set("next_cursor", p.NextCursor) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// SearchDocsPublic — Search for Docs
// GET /workspaces/%s/docs
func SearchDocsPublic(ctx context.Context, client *api.Client, workspaceId string, opts ...SearchDocsPublicParams) (*clickupv3.PublicDocsDocsSearchResultDto, error) {
	var resp clickupv3.PublicDocsDocsSearchResultDto
	path := fmt.Sprintf("workspaces/%s/docs", workspaceId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateChatChannel — Update a Channel
// PATCH /workspaces/%s/chat/channels/%s
func UpdateChatChannel(ctx context.Context, client *api.Client, workspaceId string, channelId string, req *clickupv3.ChatUpdateChatChannel) error {
	path := fmt.Sprintf("workspaces/%s/chat/channels/%s", workspaceId, channelId)
	return do(ctx, client, "PATCH", path, req, nil)
}

