// Code generated by gen-api from OpenAPI spec; DO NOT EDIT.

package apiv2

import (
	"context"
	"fmt"
	"net/url"
	"strconv"

	"github.com/toppynl/clickup-cli/internal/api"
	clickupv2 "github.com/toppynl/clickup-cli/api/clickupv2"
)

// Ensure imports are used.
var _ = fmt.Sprintf
var _ = url.Values{}
var _ = strconv.Itoa

// AddDependencyParams holds optional query parameters for AddDependency.
type AddDependencyParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p AddDependencyParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// AddDependency — Add Dependency
// POST /task/%s/dependency
func AddDependency(ctx context.Context, client *api.Client, taskId string, req *clickupv2.AddDependencyJSONRequest, opts ...AddDependencyParams) (*clickupv2.AddDependencyJSONResponse, error) {
	var resp clickupv2.AddDependencyJSONResponse
	path := fmt.Sprintf("task/%s/dependency", taskId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// AddGuestToFolderParams holds optional query parameters for AddGuestToFolder.
type AddGuestToFolderParams struct {
	IncludeShared bool `url:"include_shared,omitempty"`
}

func (p AddGuestToFolderParams) encode() string {
	q := url.Values{}
	if p.IncludeShared { q.Set("include_shared", "true") }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// AddGuestToFolder — Add Guest To Folder
// POST /folder/%s/guest/%s
func AddGuestToFolder(ctx context.Context, client *api.Client, folderId string, guestId string, req *clickupv2.AddGuestToFolderJSONRequest, opts ...AddGuestToFolderParams) (*clickupv2.AddGuestToFolderJSONResponse, error) {
	var resp clickupv2.AddGuestToFolderJSONResponse
	path := fmt.Sprintf("folder/%s/guest/%s", folderId, guestId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// AddGuestToListParams holds optional query parameters for AddGuestToList.
type AddGuestToListParams struct {
	IncludeShared bool `url:"include_shared,omitempty"`
}

func (p AddGuestToListParams) encode() string {
	q := url.Values{}
	if p.IncludeShared { q.Set("include_shared", "true") }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// AddGuestToList — Add Guest To List
// POST /list/%s/guest/%s
func AddGuestToList(ctx context.Context, client *api.Client, listId string, guestId string, req *clickupv2.AddGuestToListJSONRequest, opts ...AddGuestToListParams) (*clickupv2.AddGuestToListJSONResponse, error) {
	var resp clickupv2.AddGuestToListJSONResponse
	path := fmt.Sprintf("list/%s/guest/%s", listId, guestId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// AddGuestToTaskParams holds optional query parameters for AddGuestToTask.
type AddGuestToTaskParams struct {
	IncludeShared bool `url:"include_shared,omitempty"`
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p AddGuestToTaskParams) encode() string {
	q := url.Values{}
	if p.IncludeShared { q.Set("include_shared", "true") }
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// AddGuestToTask — Add Guest To Task
// POST /task/%s/guest/%s
func AddGuestToTask(ctx context.Context, client *api.Client, taskId string, guestId string, req *clickupv2.AddGuestToTaskJSONRequest, opts ...AddGuestToTaskParams) (*clickupv2.AddGuestToTaskJSONResponse, error) {
	var resp clickupv2.AddGuestToTaskJSONResponse
	path := fmt.Sprintf("task/%s/guest/%s", taskId, guestId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// AddTagToTaskParams holds optional query parameters for AddTagToTask.
type AddTagToTaskParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p AddTagToTaskParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// AddTagToTask — Add Tag To Task
// POST /task/%s/tag/%s
func AddTagToTask(ctx context.Context, client *api.Client, taskId string, tagName string, opts ...AddTagToTaskParams) (*clickupv2.AddTagToTaskJSONResponse, error) {
	var resp clickupv2.AddTagToTaskJSONResponse
	path := fmt.Sprintf("task/%s/tag/%s", taskId, tagName)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "POST", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// AddTaskLinkParams holds optional query parameters for AddTaskLink.
type AddTaskLinkParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p AddTaskLinkParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// AddTaskLink — Add Task Link
// POST /task/%s/link/%s
func AddTaskLink(ctx context.Context, client *api.Client, taskId string, linksTo string, opts ...AddTaskLinkParams) (*clickupv2.AddTaskLinkJSONResponse, error) {
	var resp clickupv2.AddTaskLinkJSONResponse
	path := fmt.Sprintf("task/%s/link/%s", taskId, linksTo)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "POST", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// AddTaskToList — Add Task To List
// POST /list/%s/task/%s
func AddTaskToList(ctx context.Context, client *api.Client, listId string, taskId string) (*clickupv2.AddTaskToListJSONResponse, error) {
	var resp clickupv2.AddTaskToListJSONResponse
	path := fmt.Sprintf("list/%s/task/%s", listId, taskId)
	if err := do(ctx, client, "POST", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Addtagsfromtimeentries — Add tags from time entries
// POST /team/%s/time_entries/tags
func Addtagsfromtimeentries(ctx context.Context, client *api.Client, teamId string, req *clickupv2.AddtagsfromtimeentriesJSONRequest) (*clickupv2.AddtagsfromtimeentriesJSONResponse, error) {
	var resp clickupv2.AddtagsfromtimeentriesJSONResponse
	path := fmt.Sprintf("team/%s/time_entries/tags", teamId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Changetagnamesfromtimeentries — Change tag names from time entries
// PUT /team/%s/time_entries/tags
func Changetagnamesfromtimeentries(ctx context.Context, client *api.Client, teamId string, req *clickupv2.ChangetagnamesfromtimeentriesJSONRequest) (*clickupv2.ChangetagnamesfromtimeentriesJSONResponse, error) {
	var resp clickupv2.ChangetagnamesfromtimeentriesJSONResponse
	path := fmt.Sprintf("team/%s/time_entries/tags", teamId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateChatViewComment — Create Chat View Comment
// POST /view/%s/comment
func CreateChatViewComment(ctx context.Context, client *api.Client, viewId string, req *clickupv2.CreateChatViewCommentJSONRequest) (*clickupv2.CreateChatViewCommentJSONResponse, error) {
	var resp clickupv2.CreateChatViewCommentJSONResponse
	path := fmt.Sprintf("view/%s/comment", viewId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateChecklistParams holds optional query parameters for CreateChecklist.
type CreateChecklistParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p CreateChecklistParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// CreateChecklist — Create Checklist
// POST /task/%s/checklist
func CreateChecklist(ctx context.Context, client *api.Client, taskId string, req *clickupv2.CreateChecklistJSONRequest, opts ...CreateChecklistParams) (*clickupv2.CreateChecklistJSONResponse, error) {
	var resp clickupv2.CreateChecklistJSONResponse
	path := fmt.Sprintf("task/%s/checklist", taskId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateChecklistItem — Create Checklist Item
// POST /checklist/%s/checklist_item
func CreateChecklistItem(ctx context.Context, client *api.Client, checklistId string, req *clickupv2.CreateChecklistItemJSONRequest) (*clickupv2.CreateChecklistItemJSONResponse, error) {
	var resp clickupv2.CreateChecklistItemJSONResponse
	path := fmt.Sprintf("checklist/%s/checklist_item", checklistId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateFolder — Create Folder
// POST /space/%s/folder
func CreateFolder(ctx context.Context, client *api.Client, spaceId string, req *clickupv2.CreateFolderJSONRequest) (*clickupv2.CreateFolderJSONResponse, error) {
	var resp clickupv2.CreateFolderJSONResponse
	path := fmt.Sprintf("space/%s/folder", spaceId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateFolderFromTemplate — Create Folder from template
// POST /space/%s/folder_template/%s
func CreateFolderFromTemplate(ctx context.Context, client *api.Client, spaceId string, templateId string, req *clickupv2.CreateFolderFromTemplateJSONRequest) (*clickupv2.CreateFolderFromTemplateJSONResponse, error) {
	var resp clickupv2.CreateFolderFromTemplateJSONResponse
	path := fmt.Sprintf("space/%s/folder_template/%s", spaceId, templateId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateFolderListFromTemplate — Create List From Template in Folder
// POST /folder/%s/list_template/%s
func CreateFolderListFromTemplate(ctx context.Context, client *api.Client, folderId string, templateId string, req *clickupv2.CreateFolderListFromTemplateJSONRequest) error {
	path := fmt.Sprintf("folder/%s/list_template/%s", folderId, templateId)
	return do(ctx, client, "POST", path, req, nil)
}

// CreateFolderView — Create Folder View
// POST /folder/%s/view
func CreateFolderView(ctx context.Context, client *api.Client, folderId string, req *clickupv2.CreateFolderViewJSONRequest) (*clickupv2.CreateFolderViewJSONResponse, error) {
	var resp clickupv2.CreateFolderViewJSONResponse
	path := fmt.Sprintf("folder/%s/view", folderId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateFolderlessList — Create Folderless List
// POST /space/%s/list
func CreateFolderlessList(ctx context.Context, client *api.Client, spaceId string, req *clickupv2.CreateFolderlessListJSONRequest) (*clickupv2.CreateFolderlessListJSONResponse, error) {
	var resp clickupv2.CreateFolderlessListJSONResponse
	path := fmt.Sprintf("space/%s/list", spaceId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateGoal — Create Goal
// POST /team/%s/goal
func CreateGoal(ctx context.Context, client *api.Client, teamId string, req *clickupv2.CreateGoalJSONRequest) (*clickupv2.CreateGoalJSONResponse, error) {
	var resp clickupv2.CreateGoalJSONResponse
	path := fmt.Sprintf("team/%s/goal", teamId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateKeyResult — Create Key Result
// POST /goal/%s/key_result
func CreateKeyResult(ctx context.Context, client *api.Client, goalId string, req *clickupv2.CreateKeyResultJSONRequest) (*clickupv2.CreateKeyResultJSONResponse, error) {
	var resp clickupv2.CreateKeyResultJSONResponse
	path := fmt.Sprintf("goal/%s/key_result", goalId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateList — Create List
// POST /folder/%s/list
func CreateList(ctx context.Context, client *api.Client, folderId string, req *clickupv2.CreateListJSONRequest) (*clickupv2.CreateListJSONResponse, error) {
	var resp clickupv2.CreateListJSONResponse
	path := fmt.Sprintf("folder/%s/list", folderId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateListComment — Create List Comment
// POST /list/%s/comment
func CreateListComment(ctx context.Context, client *api.Client, listId string, req *clickupv2.CreateListCommentJSONRequest) (*clickupv2.CreateListCommentJSONResponse, error) {
	var resp clickupv2.CreateListCommentJSONResponse
	path := fmt.Sprintf("list/%s/comment", listId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateListView — Create List View
// POST /list/%s/view
func CreateListView(ctx context.Context, client *api.Client, listId string, req *clickupv2.CreateListViewJSONRequest) (*clickupv2.CreateListViewJSONResponse, error) {
	var resp clickupv2.CreateListViewJSONResponse
	path := fmt.Sprintf("list/%s/view", listId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateSpace — Create Space
// POST /team/%s/space
func CreateSpace(ctx context.Context, client *api.Client, teamId string, req *clickupv2.CreateSpaceJSONRequest) (*clickupv2.CreateSpaceJSONResponse, error) {
	var resp clickupv2.CreateSpaceJSONResponse
	path := fmt.Sprintf("team/%s/space", teamId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateSpaceListFromTemplate — Create List From Template in Space
// POST /space/%s/list_template/%s
func CreateSpaceListFromTemplate(ctx context.Context, client *api.Client, spaceId string, templateId string, req *clickupv2.CreateSpaceListFromTemplateJSONRequest) (*clickupv2.CreateSpaceListFromTemplateJSONResponse, error) {
	var resp clickupv2.CreateSpaceListFromTemplateJSONResponse
	path := fmt.Sprintf("space/%s/list_template/%s", spaceId, templateId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateSpaceTag — Create Space Tag
// POST /space/%s/tag
func CreateSpaceTag(ctx context.Context, client *api.Client, spaceId string, req *clickupv2.CreateSpaceTagJSONRequest) (*clickupv2.CreateSpaceTagJSONResponse, error) {
	var resp clickupv2.CreateSpaceTagJSONResponse
	path := fmt.Sprintf("space/%s/tag", spaceId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateSpaceView — Create Space View
// POST /space/%s/view
func CreateSpaceView(ctx context.Context, client *api.Client, spaceId string, req *clickupv2.CreateSpaceViewJSONRequest) (*clickupv2.CreateSpaceViewJSONResponse, error) {
	var resp clickupv2.CreateSpaceViewJSONResponse
	path := fmt.Sprintf("space/%s/view", spaceId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateTask — Create Task
// POST /list/%s/task
func CreateTask(ctx context.Context, client *api.Client, listId string, req *clickupv2.CreateTaskJSONRequest) (*clickupv2.CreateTaskJSONResponse, error) {
	var resp clickupv2.CreateTaskJSONResponse
	path := fmt.Sprintf("list/%s/task", listId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateTaskCommentParams holds optional query parameters for CreateTaskComment.
type CreateTaskCommentParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p CreateTaskCommentParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// CreateTaskComment — Create Task Comment
// POST /task/%s/comment
func CreateTaskComment(ctx context.Context, client *api.Client, taskId string, req *clickupv2.CreateTaskCommentJSONRequest, opts ...CreateTaskCommentParams) (*clickupv2.CreateTaskCommentJSONResponse, error) {
	var resp clickupv2.CreateTaskCommentJSONResponse
	path := fmt.Sprintf("task/%s/comment", taskId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateTaskFromTemplate — Create Task From Template
// POST /list/%s/taskTemplate/%s
func CreateTaskFromTemplate(ctx context.Context, client *api.Client, listId string, templateId string, req *clickupv2.CreateTaskFromTemplateJSONRequest) (*clickupv2.CreateTaskFromTemplateJSONResponse, error) {
	var resp clickupv2.CreateTaskFromTemplateJSONResponse
	path := fmt.Sprintf("list/%s/taskTemplate/%s", listId, templateId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateTeamView — Create Workspace (Everything level) View
// POST /team/%s/view
func CreateTeamView(ctx context.Context, client *api.Client, teamId string, req *clickupv2.CreateTeamViewJSONRequest) (*clickupv2.CreateTeamViewJSONResponse, error) {
	var resp clickupv2.CreateTeamViewJSONResponse
	path := fmt.Sprintf("team/%s/view", teamId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateUserGroup — Create Group
// POST /team/%s/group
func CreateUserGroup(ctx context.Context, client *api.Client, teamId string, req *clickupv2.CreateUserGroupJSONRequest) (*clickupv2.CreateUserGroupJSONResponse, error) {
	var resp clickupv2.CreateUserGroupJSONResponse
	path := fmt.Sprintf("team/%s/group", teamId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateWebhook — Create Webhook
// POST /team/%s/webhook
func CreateWebhook(ctx context.Context, client *api.Client, teamId string, req *clickupv2.CreateWebhookJSONRequest) (*clickupv2.CreateWebhookJSONResponse, error) {
	var resp clickupv2.CreateWebhookJSONResponse
	path := fmt.Sprintf("team/%s/webhook", teamId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreateatimeentryParams holds optional query parameters for Createatimeentry.
type CreateatimeentryParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p CreateatimeentryParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// Createatimeentry — Create a time entry
// POST /team/%s/time_entries
func Createatimeentry(ctx context.Context, client *api.Client, teamId string, req *clickupv2.CreateatimeentryJSONRequest, opts ...CreateatimeentryParams) (*clickupv2.CreateatimeentryJSONResponse, error) {
	var resp clickupv2.CreateatimeentryJSONResponse
	path := fmt.Sprintf("team/%s/time_entries", teamId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteChecklist — Delete Checklist
// DELETE /checklist/%s
func DeleteChecklist(ctx context.Context, client *api.Client, checklistId string) (*clickupv2.DeleteChecklistJSONResponse, error) {
	var resp clickupv2.DeleteChecklistJSONResponse
	path := fmt.Sprintf("checklist/%s", checklistId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteChecklistItem — Delete Checklist Item
// DELETE /checklist/%s/checklist_item/%s
func DeleteChecklistItem(ctx context.Context, client *api.Client, checklistId string, checklistItemId string) (*clickupv2.DeleteChecklistItemJSONResponse, error) {
	var resp clickupv2.DeleteChecklistItemJSONResponse
	path := fmt.Sprintf("checklist/%s/checklist_item/%s", checklistId, checklistItemId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteComment — Delete Comment
// DELETE /comment/%s
func DeleteComment(ctx context.Context, client *api.Client, commentId string) (*clickupv2.DeleteCommentJSONResponse, error) {
	var resp clickupv2.DeleteCommentJSONResponse
	path := fmt.Sprintf("comment/%s", commentId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteDependencyParams holds optional query parameters for DeleteDependency.
type DeleteDependencyParams struct {
	DependsOn string `url:"depends_on,omitempty"`
	DependencyOf string `url:"dependency_of,omitempty"`
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p DeleteDependencyParams) encode() string {
	q := url.Values{}
	if p.DependsOn != "" { q.Set("depends_on", p.DependsOn) }
	if p.DependencyOf != "" { q.Set("dependency_of", p.DependencyOf) }
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// DeleteDependency — Delete Dependency
// DELETE /task/%s/dependency
func DeleteDependency(ctx context.Context, client *api.Client, taskId string, opts ...DeleteDependencyParams) (*clickupv2.DeleteDependencyJSONResponse, error) {
	var resp clickupv2.DeleteDependencyJSONResponse
	path := fmt.Sprintf("task/%s/dependency", taskId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteFolder — Delete Folder
// DELETE /folder/%s
func DeleteFolder(ctx context.Context, client *api.Client, folderId string) (*clickupv2.DeleteFolderJSONResponse, error) {
	var resp clickupv2.DeleteFolderJSONResponse
	path := fmt.Sprintf("folder/%s", folderId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteGoal — Delete Goal
// DELETE /goal/%s
func DeleteGoal(ctx context.Context, client *api.Client, goalId string) (*clickupv2.DeleteGoalJSONResponse, error) {
	var resp clickupv2.DeleteGoalJSONResponse
	path := fmt.Sprintf("goal/%s", goalId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteKeyResult — Delete Key Result
// DELETE /key_result/%s
func DeleteKeyResult(ctx context.Context, client *api.Client, keyResultId string) (*clickupv2.DeleteKeyResultJSONResponse, error) {
	var resp clickupv2.DeleteKeyResultJSONResponse
	path := fmt.Sprintf("key_result/%s", keyResultId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteList — Delete List
// DELETE /list/%s
func DeleteList(ctx context.Context, client *api.Client, listId string) (*clickupv2.DeleteListJSONResponse, error) {
	var resp clickupv2.DeleteListJSONResponse
	path := fmt.Sprintf("list/%s", listId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteSpace — Delete Space
// DELETE /space/%s
func DeleteSpace(ctx context.Context, client *api.Client, spaceId string) (*clickupv2.DeleteSpaceJSONResponse, error) {
	var resp clickupv2.DeleteSpaceJSONResponse
	path := fmt.Sprintf("space/%s", spaceId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteSpaceTag — Delete Space Tag
// DELETE /space/%s/tag/%s
func DeleteSpaceTag(ctx context.Context, client *api.Client, spaceId string, tagName string, req *clickupv2.DeleteSpaceTagJSONRequest) (*clickupv2.DeleteSpaceTagJSONResponse, error) {
	var resp clickupv2.DeleteSpaceTagJSONResponse
	path := fmt.Sprintf("space/%s/tag/%s", spaceId, tagName)
	if err := do(ctx, client, "DELETE", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteTaskParams holds optional query parameters for DeleteTask.
type DeleteTaskParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p DeleteTaskParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// DeleteTask — Delete Task
// DELETE /task/%s
func DeleteTask(ctx context.Context, client *api.Client, taskId string, opts ...DeleteTaskParams) error {
	path := fmt.Sprintf("task/%s", taskId)
	if len(opts) > 0 { path += opts[0].encode() }
	return do(ctx, client, "DELETE", path, nil, nil)
}

// DeleteTaskLinkParams holds optional query parameters for DeleteTaskLink.
type DeleteTaskLinkParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p DeleteTaskLinkParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// DeleteTaskLink — Delete Task Link
// DELETE /task/%s/link/%s
func DeleteTaskLink(ctx context.Context, client *api.Client, taskId string, linksTo string, opts ...DeleteTaskLinkParams) (*clickupv2.DeleteTaskLinkJSONResponse, error) {
	var resp clickupv2.DeleteTaskLinkJSONResponse
	path := fmt.Sprintf("task/%s/link/%s", taskId, linksTo)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteTeam — Delete Group
// DELETE /group/%s
func DeleteTeam(ctx context.Context, client *api.Client, groupId string) (*clickupv2.DeleteTeamJSONResponse, error) {
	var resp clickupv2.DeleteTeamJSONResponse
	path := fmt.Sprintf("group/%s", groupId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteView — Delete View
// DELETE /view/%s
func DeleteView(ctx context.Context, client *api.Client, viewId string) (*clickupv2.DeleteViewJSONResponse, error) {
	var resp clickupv2.DeleteViewJSONResponse
	path := fmt.Sprintf("view/%s", viewId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteWebhook — Delete Webhook
// DELETE /webhook/%s
func DeleteWebhook(ctx context.Context, client *api.Client, webhookId string) (*clickupv2.DeleteWebhookJSONResponse, error) {
	var resp clickupv2.DeleteWebhookJSONResponse
	path := fmt.Sprintf("webhook/%s", webhookId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteatimeEntry — Delete a time Entry
// DELETE /team/%s/time_entries/%s
func DeleteatimeEntry(ctx context.Context, client *api.Client, teamId string, timerId string) (*clickupv2.DeleteatimeEntryJSONResponse, error) {
	var resp clickupv2.DeleteatimeEntryJSONResponse
	path := fmt.Sprintf("team/%s/time_entries/%s", teamId, timerId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeletetimetrackedParams holds optional query parameters for Deletetimetracked.
type DeletetimetrackedParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p DeletetimetrackedParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// Deletetimetracked — Delete time tracked
// DELETE /task/%s/time/%s
func Deletetimetracked(ctx context.Context, client *api.Client, taskId string, intervalId string, opts ...DeletetimetrackedParams) (*clickupv2.DeletetimetrackedJSONResponse, error) {
	var resp clickupv2.DeletetimetrackedJSONResponse
	path := fmt.Sprintf("task/%s/time/%s", taskId, intervalId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// EditChecklist — Edit Checklist
// PUT /checklist/%s
func EditChecklist(ctx context.Context, client *api.Client, checklistId string, req *clickupv2.EditChecklistJSONRequest) (*clickupv2.EditChecklistJSONResponse, error) {
	var resp clickupv2.EditChecklistJSONResponse
	path := fmt.Sprintf("checklist/%s", checklistId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// EditChecklistItem — Edit Checklist Item
// PUT /checklist/%s/checklist_item/%s
func EditChecklistItem(ctx context.Context, client *api.Client, checklistId string, checklistItemId string, req *clickupv2.EditChecklistItemJSONRequest) (*clickupv2.EditChecklistItemJSONResponse, error) {
	var resp clickupv2.EditChecklistItemJSONResponse
	path := fmt.Sprintf("checklist/%s/checklist_item/%s", checklistId, checklistItemId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// EditGuestOnWorkspace — Edit Guest On Workspace
// PUT /team/%s/guest/%s
func EditGuestOnWorkspace(ctx context.Context, client *api.Client, teamId string, guestId string, req *clickupv2.EditGuestOnWorkspaceJSONRequest) (*clickupv2.EditGuestOnWorkspaceJSONResponse, error) {
	var resp clickupv2.EditGuestOnWorkspaceJSONResponse
	path := fmt.Sprintf("team/%s/guest/%s", teamId, guestId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// EditKeyResult — Edit Key Result
// PUT /key_result/%s
func EditKeyResult(ctx context.Context, client *api.Client, keyResultId string, req *clickupv2.EditKeyResultJSONRequest) (*clickupv2.EditKeyResultJSONResponse, error) {
	var resp clickupv2.EditKeyResultJSONResponse
	path := fmt.Sprintf("key_result/%s", keyResultId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// EditSpaceTag — Edit Space Tag
// PUT /space/%s/tag/%s
func EditSpaceTag(ctx context.Context, client *api.Client, spaceId string, tagName string, req *clickupv2.EditSpaceTagJSONRequest) (*clickupv2.EditSpaceTagJSONResponse, error) {
	var resp clickupv2.EditSpaceTagJSONResponse
	path := fmt.Sprintf("space/%s/tag/%s", spaceId, tagName)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// EditUserOnWorkspace — Edit User On Workspace
// PUT /team/%s/user/%s
func EditUserOnWorkspace(ctx context.Context, client *api.Client, teamId string, userId string, req *clickupv2.EditUserOnWorkspaceJSONRequest) (*clickupv2.EditUserOnWorkspaceJSONResponse, error) {
	var resp clickupv2.EditUserOnWorkspaceJSONResponse
	path := fmt.Sprintf("team/%s/user/%s", teamId, userId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// EdittimetrackedParams holds optional query parameters for Edittimetracked.
type EdittimetrackedParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p EdittimetrackedParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// Edittimetracked — Edit time tracked
// PUT /task/%s/time/%s
func Edittimetracked(ctx context.Context, client *api.Client, taskId string, intervalId string, req *clickupv2.EdittimetrackedJSONRequest, opts ...EdittimetrackedParams) (*clickupv2.EdittimetrackedJSONResponse, error) {
	var resp clickupv2.EdittimetrackedJSONResponse
	path := fmt.Sprintf("task/%s/time/%s", taskId, intervalId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetAccessToken — Get Access Token
// POST /oauth/token
func GetAccessToken(ctx context.Context, client *api.Client, req *clickupv2.GetAccessTokenJSONRequest) (*clickupv2.GetAccessTokenJSONResponse, error) {
	var resp clickupv2.GetAccessTokenJSONResponse
	path := "oauth/token"
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetAccessibleCustomFields — Get List Custom Fields
// GET /list/%s/field
func GetAccessibleCustomFields(ctx context.Context, client *api.Client, listId string) (*clickupv2.GetAccessibleCustomFieldsJSONResponse, error) {
	var resp clickupv2.GetAccessibleCustomFieldsJSONResponse
	path := fmt.Sprintf("list/%s/field", listId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetAuthorizedTeams — Get Authorized Workspaces
// GET /team
func GetAuthorizedTeams(ctx context.Context, client *api.Client) (*clickupv2.GetAuthorizedTeamsJSONResponse, error) {
	var resp clickupv2.GetAuthorizedTeamsJSONResponse
	path := "team"
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetAuthorizedUser — Get Authorized User
// GET /user
func GetAuthorizedUser(ctx context.Context, client *api.Client) (*clickupv2.GetAuthorizedUserJSONResponse, error) {
	var resp clickupv2.GetAuthorizedUserJSONResponse
	path := "user"
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetBulkTasksTimeinStatusParams holds optional query parameters for GetBulkTasksTimeinStatus.
type GetBulkTasksTimeinStatusParams struct {
	TaskIds string `url:"task_ids,omitempty"`
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p GetBulkTasksTimeinStatusParams) encode() string {
	q := url.Values{}
	if p.TaskIds != "" { q.Set("task_ids", p.TaskIds) }
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetBulkTasksTimeinStatus — Get Bulk Tasks' Time in Status
// GET /task/bulk_time_in_status/task_ids
func GetBulkTasksTimeinStatus(ctx context.Context, client *api.Client, opts ...GetBulkTasksTimeinStatusParams) (*clickupv2.GetBulkTasksTimeinStatusJSONResponse, error) {
	var resp clickupv2.GetBulkTasksTimeinStatusJSONResponse
	path := "task/bulk_time_in_status/task_ids"
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetChatViewCommentsParams holds optional query parameters for GetChatViewComments.
type GetChatViewCommentsParams struct {
	Start int `url:"start,omitempty"`
	StartId string `url:"start_id,omitempty"`
}

func (p GetChatViewCommentsParams) encode() string {
	q := url.Values{}
	if p.Start != 0 { q.Set("start", strconv.Itoa(p.Start)) }
	if p.StartId != "" { q.Set("start_id", p.StartId) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetChatViewComments — Get Chat View Comments
// GET /view/%s/comment
func GetChatViewComments(ctx context.Context, client *api.Client, viewId string, opts ...GetChatViewCommentsParams) (*clickupv2.GetChatViewCommentsJSONResponse, error) {
	var resp clickupv2.GetChatViewCommentsJSONResponse
	path := fmt.Sprintf("view/%s/comment", viewId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetCustomItems — Get Custom Task Types
// GET /team/%s/custom_item
func GetCustomItems(ctx context.Context, client *api.Client, teamId string) (*clickupv2.GetCustomItemsJSONResponse, error) {
	var resp clickupv2.GetCustomItemsJSONResponse
	path := fmt.Sprintf("team/%s/custom_item", teamId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetCustomRolesParams holds optional query parameters for GetCustomRoles.
type GetCustomRolesParams struct {
	IncludeMembers bool `url:"include_members,omitempty"`
}

func (p GetCustomRolesParams) encode() string {
	q := url.Values{}
	if p.IncludeMembers { q.Set("include_members", "true") }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetCustomRoles — Get Custom Roles
// GET /team/%s/customroles
func GetCustomRoles(ctx context.Context, client *api.Client, teamId string, opts ...GetCustomRolesParams) (*clickupv2.GetCustomRolesJSONResponse, error) {
	var resp clickupv2.GetCustomRolesJSONResponse
	path := fmt.Sprintf("team/%s/customroles", teamId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetFilteredTeamTasksParams holds optional query parameters for GetFilteredTeamTasks.
type GetFilteredTeamTasksParams struct {
	Page int `url:"page,omitempty"`
	OrderBy string `url:"order_by,omitempty"`
	Reverse bool `url:"reverse,omitempty"`
	Subtasks bool `url:"subtasks,omitempty"`
	SpaceIds string `url:"space_ids[],omitempty"`
	ProjectIds string `url:"project_ids[],omitempty"`
	ListIds string `url:"list_ids[],omitempty"`
	Statuses string `url:"statuses[],omitempty"`
	IncludeClosed bool `url:"include_closed,omitempty"`
	Assignees string `url:"assignees[],omitempty"`
	Tags string `url:"tags[],omitempty"`
	DueDateGt int `url:"due_date_gt,omitempty"`
	DueDateLt int `url:"due_date_lt,omitempty"`
	DateCreatedGt int `url:"date_created_gt,omitempty"`
	DateCreatedLt int `url:"date_created_lt,omitempty"`
	DateUpdatedGt int `url:"date_updated_gt,omitempty"`
	DateUpdatedLt int `url:"date_updated_lt,omitempty"`
	DateDoneGt int `url:"date_done_gt,omitempty"`
	DateDoneLt int `url:"date_done_lt,omitempty"`
	CustomFields string `url:"custom_fields,omitempty"`
	Parent string `url:"parent,omitempty"`
	IncludeMarkdownDescription bool `url:"include_markdown_description,omitempty"`
	CustomItems string `url:"custom_items[],omitempty"`
}

func (p GetFilteredTeamTasksParams) encode() string {
	q := url.Values{}
	if p.Page != 0 { q.Set("page", strconv.Itoa(p.Page)) }
	if p.OrderBy != "" { q.Set("order_by", p.OrderBy) }
	if p.Reverse { q.Set("reverse", "true") }
	if p.Subtasks { q.Set("subtasks", "true") }
	if p.SpaceIds != "" { q.Set("space_ids[]", p.SpaceIds) }
	if p.ProjectIds != "" { q.Set("project_ids[]", p.ProjectIds) }
	if p.ListIds != "" { q.Set("list_ids[]", p.ListIds) }
	if p.Statuses != "" { q.Set("statuses[]", p.Statuses) }
	if p.IncludeClosed { q.Set("include_closed", "true") }
	if p.Assignees != "" { q.Set("assignees[]", p.Assignees) }
	if p.Tags != "" { q.Set("tags[]", p.Tags) }
	if p.DueDateGt != 0 { q.Set("due_date_gt", strconv.Itoa(p.DueDateGt)) }
	if p.DueDateLt != 0 { q.Set("due_date_lt", strconv.Itoa(p.DueDateLt)) }
	if p.DateCreatedGt != 0 { q.Set("date_created_gt", strconv.Itoa(p.DateCreatedGt)) }
	if p.DateCreatedLt != 0 { q.Set("date_created_lt", strconv.Itoa(p.DateCreatedLt)) }
	if p.DateUpdatedGt != 0 { q.Set("date_updated_gt", strconv.Itoa(p.DateUpdatedGt)) }
	if p.DateUpdatedLt != 0 { q.Set("date_updated_lt", strconv.Itoa(p.DateUpdatedLt)) }
	if p.DateDoneGt != 0 { q.Set("date_done_gt", strconv.Itoa(p.DateDoneGt)) }
	if p.DateDoneLt != 0 { q.Set("date_done_lt", strconv.Itoa(p.DateDoneLt)) }
	if p.CustomFields != "" { q.Set("custom_fields", p.CustomFields) }
	if p.Parent != "" { q.Set("parent", p.Parent) }
	if p.IncludeMarkdownDescription { q.Set("include_markdown_description", "true") }
	if p.CustomItems != "" { q.Set("custom_items[]", p.CustomItems) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetFilteredTeamTasks — Get Filtered Team Tasks
// GET /team/%s/task
func GetFilteredTeamTasks(ctx context.Context, client *api.Client, teamId string, opts ...GetFilteredTeamTasksParams) (*clickupv2.GetFilteredTeamTasksJSONResponse, error) {
	var resp clickupv2.GetFilteredTeamTasksJSONResponse
	path := fmt.Sprintf("team/%s/task", teamId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetFolder — Get Folder
// GET /folder/%s
func GetFolder(ctx context.Context, client *api.Client, folderId string) (*clickupv2.GetFolderJSONResponse, error) {
	var resp clickupv2.GetFolderJSONResponse
	path := fmt.Sprintf("folder/%s", folderId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetFolderAvailableFields — Get Folder Custom Fields
// GET /folder/%s/field
func GetFolderAvailableFields(ctx context.Context, client *api.Client, folderId string) (*clickupv2.GetFolderAvailableFieldsJSONResponse, error) {
	var resp clickupv2.GetFolderAvailableFieldsJSONResponse
	path := fmt.Sprintf("folder/%s/field", folderId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetFolderTemplates — Get Folder Templates
// GET /team/%s/folder_template
func GetFolderTemplates(ctx context.Context, client *api.Client, teamId string) (*clickupv2.GetFolderTemplatesJSONResponse, error) {
	var resp clickupv2.GetFolderTemplatesJSONResponse
	path := fmt.Sprintf("team/%s/folder_template", teamId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetFolderViews — Get Folder Views
// GET /folder/%s/view
func GetFolderViews(ctx context.Context, client *api.Client, folderId string) (*clickupv2.GetFolderViewsJSONResponse, error) {
	var resp clickupv2.GetFolderViewsJSONResponse
	path := fmt.Sprintf("folder/%s/view", folderId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetFolderlessListsParams holds optional query parameters for GetFolderlessLists.
type GetFolderlessListsParams struct {
	Archived bool `url:"archived,omitempty"`
}

func (p GetFolderlessListsParams) encode() string {
	q := url.Values{}
	if p.Archived { q.Set("archived", "true") }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetFolderlessLists — Get Folderless Lists
// GET /space/%s/list
func GetFolderlessLists(ctx context.Context, client *api.Client, spaceId string, opts ...GetFolderlessListsParams) (*clickupv2.GetFolderlessListsJSONResponse, error) {
	var resp clickupv2.GetFolderlessListsJSONResponse
	path := fmt.Sprintf("space/%s/list", spaceId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetFoldersParams holds optional query parameters for GetFolders.
type GetFoldersParams struct {
	Archived bool `url:"archived,omitempty"`
}

func (p GetFoldersParams) encode() string {
	q := url.Values{}
	if p.Archived { q.Set("archived", "true") }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetFolders — Get Folders
// GET /space/%s/folder
func GetFolders(ctx context.Context, client *api.Client, spaceId string, opts ...GetFoldersParams) (*clickupv2.GetFoldersJSONResponse, error) {
	var resp clickupv2.GetFoldersJSONResponse
	path := fmt.Sprintf("space/%s/folder", spaceId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetGoal — Get Goal
// GET /goal/%s
func GetGoal(ctx context.Context, client *api.Client, goalId string) (*clickupv2.GetGoalJSONResponse, error) {
	var resp clickupv2.GetGoalJSONResponse
	path := fmt.Sprintf("goal/%s", goalId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetGoalsParams holds optional query parameters for GetGoals.
type GetGoalsParams struct {
	IncludeCompleted bool `url:"include_completed,omitempty"`
}

func (p GetGoalsParams) encode() string {
	q := url.Values{}
	if p.IncludeCompleted { q.Set("include_completed", "true") }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetGoals — Get Goals
// GET /team/%s/goal
func GetGoals(ctx context.Context, client *api.Client, teamId string, opts ...GetGoalsParams) (*clickupv2.GetGoalsJSONResponse, error) {
	var resp clickupv2.GetGoalsJSONResponse
	path := fmt.Sprintf("team/%s/goal", teamId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetGuest — Get Guest
// GET /team/%s/guest/%s
func GetGuest(ctx context.Context, client *api.Client, teamId string, guestId string) (*clickupv2.GetGuestJSONResponse, error) {
	var resp clickupv2.GetGuestJSONResponse
	path := fmt.Sprintf("team/%s/guest/%s", teamId, guestId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetList — Get List
// GET /list/%s
func GetList(ctx context.Context, client *api.Client, listId string) (*clickupv2.GetListJSONResponse, error) {
	var resp clickupv2.GetListJSONResponse
	path := fmt.Sprintf("list/%s", listId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetListCommentsParams holds optional query parameters for GetListComments.
type GetListCommentsParams struct {
	Start int `url:"start,omitempty"`
	StartId string `url:"start_id,omitempty"`
}

func (p GetListCommentsParams) encode() string {
	q := url.Values{}
	if p.Start != 0 { q.Set("start", strconv.Itoa(p.Start)) }
	if p.StartId != "" { q.Set("start_id", p.StartId) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetListComments — Get List Comments
// GET /list/%s/comment
func GetListComments(ctx context.Context, client *api.Client, listId string, opts ...GetListCommentsParams) (*clickupv2.GetListCommentsJSONResponse, error) {
	var resp clickupv2.GetListCommentsJSONResponse
	path := fmt.Sprintf("list/%s/comment", listId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetListMembers — Get List Members
// GET /list/%s/member
func GetListMembers(ctx context.Context, client *api.Client, listId string) (*clickupv2.GetListMembersJSONResponse, error) {
	var resp clickupv2.GetListMembersJSONResponse
	path := fmt.Sprintf("list/%s/member", listId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetListTemplates — Get List Templates
// GET /team/%s/list_template
func GetListTemplates(ctx context.Context, client *api.Client, teamId string) (*clickupv2.GetListTemplatesJSONResponse, error) {
	var resp clickupv2.GetListTemplatesJSONResponse
	path := fmt.Sprintf("team/%s/list_template", teamId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetListViews — Get List Views
// GET /list/%s/view
func GetListViews(ctx context.Context, client *api.Client, listId string) (*clickupv2.GetListViewsJSONResponse, error) {
	var resp clickupv2.GetListViewsJSONResponse
	path := fmt.Sprintf("list/%s/view", listId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetListsParams holds optional query parameters for GetLists.
type GetListsParams struct {
	Archived bool `url:"archived,omitempty"`
}

func (p GetListsParams) encode() string {
	q := url.Values{}
	if p.Archived { q.Set("archived", "true") }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetLists — Get Lists
// GET /folder/%s/list
func GetLists(ctx context.Context, client *api.Client, folderId string, opts ...GetListsParams) (*clickupv2.GetListsJSONResponse, error) {
	var resp clickupv2.GetListsJSONResponse
	path := fmt.Sprintf("folder/%s/list", folderId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetSpace — Get Space
// GET /space/%s
func GetSpace(ctx context.Context, client *api.Client, spaceId string) (*clickupv2.GetSpaceJSONResponse, error) {
	var resp clickupv2.GetSpaceJSONResponse
	path := fmt.Sprintf("space/%s", spaceId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetSpaceAvailableFields — Get Space Custom Fields
// GET /space/%s/field
func GetSpaceAvailableFields(ctx context.Context, client *api.Client, spaceId string) (*clickupv2.GetSpaceAvailableFieldsJSONResponse, error) {
	var resp clickupv2.GetSpaceAvailableFieldsJSONResponse
	path := fmt.Sprintf("space/%s/field", spaceId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetSpaceTags — Get Space Tags
// GET /space/%s/tag
func GetSpaceTags(ctx context.Context, client *api.Client, spaceId string) (*clickupv2.GetSpaceTagsJSONResponse, error) {
	var resp clickupv2.GetSpaceTagsJSONResponse
	path := fmt.Sprintf("space/%s/tag", spaceId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetSpaceViews — Get Space Views
// GET /space/%s/view
func GetSpaceViews(ctx context.Context, client *api.Client, spaceId string) (*clickupv2.GetSpaceViewsJSONResponse, error) {
	var resp clickupv2.GetSpaceViewsJSONResponse
	path := fmt.Sprintf("space/%s/view", spaceId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetSpacesParams holds optional query parameters for GetSpaces.
type GetSpacesParams struct {
	Archived bool `url:"archived,omitempty"`
}

func (p GetSpacesParams) encode() string {
	q := url.Values{}
	if p.Archived { q.Set("archived", "true") }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetSpaces — Get Spaces
// GET /team/%s/space
func GetSpaces(ctx context.Context, client *api.Client, teamId string, opts ...GetSpacesParams) (*clickupv2.GetSpacesJSONResponse, error) {
	var resp clickupv2.GetSpacesJSONResponse
	path := fmt.Sprintf("team/%s/space", teamId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetTaskParams holds optional query parameters for GetTask.
type GetTaskParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
	IncludeSubtasks bool `url:"include_subtasks,omitempty"`
	IncludeMarkdownDescription bool `url:"include_markdown_description,omitempty"`
	CustomFields string `url:"custom_fields,omitempty"`
}

func (p GetTaskParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if p.IncludeSubtasks { q.Set("include_subtasks", "true") }
	if p.IncludeMarkdownDescription { q.Set("include_markdown_description", "true") }
	if p.CustomFields != "" { q.Set("custom_fields", p.CustomFields) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetTask — Get Task
// GET /task/%s
func GetTask(ctx context.Context, client *api.Client, taskId string, opts ...GetTaskParams) (*clickupv2.GetTaskJSONResponse, error) {
	var resp clickupv2.GetTaskJSONResponse
	path := fmt.Sprintf("task/%s", taskId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetTaskCommentsParams holds optional query parameters for GetTaskComments.
type GetTaskCommentsParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
	Start int `url:"start,omitempty"`
	StartId string `url:"start_id,omitempty"`
}

func (p GetTaskCommentsParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if p.Start != 0 { q.Set("start", strconv.Itoa(p.Start)) }
	if p.StartId != "" { q.Set("start_id", p.StartId) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetTaskComments — Get Task Comments
// GET /task/%s/comment
func GetTaskComments(ctx context.Context, client *api.Client, taskId string, opts ...GetTaskCommentsParams) (*clickupv2.GetTaskCommentsJSONResponse, error) {
	var resp clickupv2.GetTaskCommentsJSONResponse
	path := fmt.Sprintf("task/%s/comment", taskId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetTaskMembers — Get Task Members
// GET /task/%s/member
func GetTaskMembers(ctx context.Context, client *api.Client, taskId string) (*clickupv2.GetTaskMembersJSONResponse, error) {
	var resp clickupv2.GetTaskMembersJSONResponse
	path := fmt.Sprintf("task/%s/member", taskId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetTaskTemplatesParams holds optional query parameters for GetTaskTemplates.
type GetTaskTemplatesParams struct {
	Page int `url:"page,omitempty"`
}

func (p GetTaskTemplatesParams) encode() string {
	q := url.Values{}
	if p.Page != 0 { q.Set("page", strconv.Itoa(p.Page)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetTaskTemplates — Get Task Templates
// GET /team/%s/taskTemplate
func GetTaskTemplates(ctx context.Context, client *api.Client, teamId string, opts ...GetTaskTemplatesParams) (*clickupv2.GetTaskTemplatesJSONResponse, error) {
	var resp clickupv2.GetTaskTemplatesJSONResponse
	path := fmt.Sprintf("team/%s/taskTemplate", teamId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetTasksParams holds optional query parameters for GetTasks.
type GetTasksParams struct {
	Archived bool `url:"archived,omitempty"`
	IncludeMarkdownDescription bool `url:"include_markdown_description,omitempty"`
	Page int `url:"page,omitempty"`
	OrderBy string `url:"order_by,omitempty"`
	Reverse bool `url:"reverse,omitempty"`
	Subtasks bool `url:"subtasks,omitempty"`
	Statuses string `url:"statuses,omitempty"`
	IncludeClosed bool `url:"include_closed,omitempty"`
	IncludeTiml bool `url:"include_timl,omitempty"`
	Assignees string `url:"assignees,omitempty"`
	Watchers string `url:"watchers,omitempty"`
	Tags string `url:"tags,omitempty"`
	DueDateGt int `url:"due_date_gt,omitempty"`
	DueDateLt int `url:"due_date_lt,omitempty"`
	DateCreatedGt int `url:"date_created_gt,omitempty"`
	DateCreatedLt int `url:"date_created_lt,omitempty"`
	DateUpdatedGt int `url:"date_updated_gt,omitempty"`
	DateUpdatedLt int `url:"date_updated_lt,omitempty"`
	DateDoneGt int `url:"date_done_gt,omitempty"`
	DateDoneLt int `url:"date_done_lt,omitempty"`
	CustomFields string `url:"custom_fields,omitempty"`
	CustomField string `url:"custom_field,omitempty"`
	CustomItems string `url:"custom_items,omitempty"`
}

func (p GetTasksParams) encode() string {
	q := url.Values{}
	if p.Archived { q.Set("archived", "true") }
	if p.IncludeMarkdownDescription { q.Set("include_markdown_description", "true") }
	if p.Page != 0 { q.Set("page", strconv.Itoa(p.Page)) }
	if p.OrderBy != "" { q.Set("order_by", p.OrderBy) }
	if p.Reverse { q.Set("reverse", "true") }
	if p.Subtasks { q.Set("subtasks", "true") }
	if p.Statuses != "" { q.Set("statuses", p.Statuses) }
	if p.IncludeClosed { q.Set("include_closed", "true") }
	if p.IncludeTiml { q.Set("include_timl", "true") }
	if p.Assignees != "" { q.Set("assignees", p.Assignees) }
	if p.Watchers != "" { q.Set("watchers", p.Watchers) }
	if p.Tags != "" { q.Set("tags", p.Tags) }
	if p.DueDateGt != 0 { q.Set("due_date_gt", strconv.Itoa(p.DueDateGt)) }
	if p.DueDateLt != 0 { q.Set("due_date_lt", strconv.Itoa(p.DueDateLt)) }
	if p.DateCreatedGt != 0 { q.Set("date_created_gt", strconv.Itoa(p.DateCreatedGt)) }
	if p.DateCreatedLt != 0 { q.Set("date_created_lt", strconv.Itoa(p.DateCreatedLt)) }
	if p.DateUpdatedGt != 0 { q.Set("date_updated_gt", strconv.Itoa(p.DateUpdatedGt)) }
	if p.DateUpdatedLt != 0 { q.Set("date_updated_lt", strconv.Itoa(p.DateUpdatedLt)) }
	if p.DateDoneGt != 0 { q.Set("date_done_gt", strconv.Itoa(p.DateDoneGt)) }
	if p.DateDoneLt != 0 { q.Set("date_done_lt", strconv.Itoa(p.DateDoneLt)) }
	if p.CustomFields != "" { q.Set("custom_fields", p.CustomFields) }
	if p.CustomField != "" { q.Set("custom_field", p.CustomField) }
	if p.CustomItems != "" { q.Set("custom_items", p.CustomItems) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetTasks — Get Tasks
// GET /list/%s/task
func GetTasks(ctx context.Context, client *api.Client, listId string, opts ...GetTasksParams) (*clickupv2.GetTasksJSONResponse, error) {
	var resp clickupv2.GetTasksJSONResponse
	path := fmt.Sprintf("list/%s/task", listId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetTasksTimeinStatusParams holds optional query parameters for GetTasksTimeinStatus.
type GetTasksTimeinStatusParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p GetTasksTimeinStatusParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetTasksTimeinStatus — Get Task's Time in Status
// GET /task/%s/time_in_status
func GetTasksTimeinStatus(ctx context.Context, client *api.Client, taskId string, opts ...GetTasksTimeinStatusParams) error {
	path := fmt.Sprintf("task/%s/time_in_status", taskId)
	if len(opts) > 0 { path += opts[0].encode() }
	return do(ctx, client, "GET", path, nil, nil)
}

// GetTeamAvailableFields — Get Workspace Custom Fields
// GET /team/%s/field
func GetTeamAvailableFields(ctx context.Context, client *api.Client, teamId string) (*clickupv2.GetTeamAvailableFieldsJSONResponse, error) {
	var resp clickupv2.GetTeamAvailableFieldsJSONResponse
	path := fmt.Sprintf("team/%s/field", teamId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetTeamViews — Get Workspace (Everything level) Views
// GET /team/%s/view
func GetTeamViews(ctx context.Context, client *api.Client, teamId string) (*clickupv2.GetTeamViewsJSONResponse, error) {
	var resp clickupv2.GetTeamViewsJSONResponse
	path := fmt.Sprintf("team/%s/view", teamId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetTeams1Params holds optional query parameters for GetTeams1.
type GetTeams1Params struct {
	TeamId float64 `url:"team_id,omitempty"`
	GroupIds string `url:"group_ids,omitempty"`
}

func (p GetTeams1Params) encode() string {
	q := url.Values{}
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if p.GroupIds != "" { q.Set("group_ids", p.GroupIds) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetTeams1 — Get Groups
// GET /group
func GetTeams1(ctx context.Context, client *api.Client, opts ...GetTeams1Params) (*clickupv2.GetTeams1JSONResponse, error) {
	var resp clickupv2.GetTeams1JSONResponse
	path := "group"
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetThreadedComments — Get Threaded Comments
// GET /comment/%s/reply
func GetThreadedComments(ctx context.Context, client *api.Client, commentId string) error {
	path := fmt.Sprintf("comment/%s/reply", commentId)
	return do(ctx, client, "GET", path, nil, nil)
}

// GetUserParams holds optional query parameters for GetUser.
type GetUserParams struct {
	IncludeShared bool `url:"include_shared,omitempty"`
}

func (p GetUserParams) encode() string {
	q := url.Values{}
	if p.IncludeShared { q.Set("include_shared", "true") }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetUser — Get User
// GET /team/%s/user/%s
func GetUser(ctx context.Context, client *api.Client, teamId string, userId string, opts ...GetUserParams) (*clickupv2.GetUserJSONResponse, error) {
	var resp clickupv2.GetUserJSONResponse
	path := fmt.Sprintf("team/%s/user/%s", teamId, userId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetView — Get View
// GET /view/%s
func GetView(ctx context.Context, client *api.Client, viewId string) (*clickupv2.GetViewJSONResponse, error) {
	var resp clickupv2.GetViewJSONResponse
	path := fmt.Sprintf("view/%s", viewId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetViewTasksParams holds optional query parameters for GetViewTasks.
type GetViewTasksParams struct {
	Page int `url:"page,omitempty"`
}

func (p GetViewTasksParams) encode() string {
	q := url.Values{}
	if p.Page != 0 { q.Set("page", strconv.Itoa(p.Page)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// GetViewTasks — Get View Tasks
// GET /view/%s/task
func GetViewTasks(ctx context.Context, client *api.Client, viewId string, opts ...GetViewTasksParams) (*clickupv2.GetViewTasksJSONResponse, error) {
	var resp clickupv2.GetViewTasksJSONResponse
	path := fmt.Sprintf("view/%s/task", viewId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetWebhooks — Get Webhooks
// GET /team/%s/webhook
func GetWebhooks(ctx context.Context, client *api.Client, teamId string) (*clickupv2.GetWebhooksJSONResponse, error) {
	var resp clickupv2.GetWebhooksJSONResponse
	path := fmt.Sprintf("team/%s/webhook", teamId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetWorkspaceplan — Get Workspace Plan
// GET /team/%s/plan
func GetWorkspaceplan(ctx context.Context, client *api.Client, teamId string) (*clickupv2.GetWorkspaceplanJSONResponse, error) {
	var resp clickupv2.GetWorkspaceplanJSONResponse
	path := fmt.Sprintf("team/%s/plan", teamId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetWorkspaceseats — Get Workspace seats
// GET /team/%s/seats
func GetWorkspaceseats(ctx context.Context, client *api.Client, teamId string) (*clickupv2.GetWorkspaceseatsJSONResponse, error) {
	var resp clickupv2.GetWorkspaceseatsJSONResponse
	path := fmt.Sprintf("team/%s/seats", teamId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Getalltagsfromtimeentries — Get all tags from time entries
// GET /team/%s/time_entries/tags
func Getalltagsfromtimeentries(ctx context.Context, client *api.Client, teamId string) (*clickupv2.GetalltagsfromtimeentriesJSONResponse, error) {
	var resp clickupv2.GetalltagsfromtimeentriesJSONResponse
	path := fmt.Sprintf("team/%s/time_entries/tags", teamId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetrunningtimeentryParams holds optional query parameters for Getrunningtimeentry.
type GetrunningtimeentryParams struct {
	Assignee float64 `url:"assignee,omitempty"`
}

func (p GetrunningtimeentryParams) encode() string {
	q := url.Values{}
	if p.Assignee != 0 { q.Set("assignee", fmt.Sprintf("%g", p.Assignee)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// Getrunningtimeentry — Get running time entry
// GET /team/%s/time_entries/current
func Getrunningtimeentry(ctx context.Context, client *api.Client, teamId string, opts ...GetrunningtimeentryParams) (*clickupv2.GetrunningtimeentryJSONResponse, error) {
	var resp clickupv2.GetrunningtimeentryJSONResponse
	path := fmt.Sprintf("team/%s/time_entries/current", teamId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetsingulartimeentryParams holds optional query parameters for Getsingulartimeentry.
type GetsingulartimeentryParams struct {
	IncludeTaskTags bool `url:"include_task_tags,omitempty"`
	IncludeLocationNames bool `url:"include_location_names,omitempty"`
	IncludeApprovalHistory bool `url:"include_approval_history,omitempty"`
	IncludeApprovalDetails bool `url:"include_approval_details,omitempty"`
}

func (p GetsingulartimeentryParams) encode() string {
	q := url.Values{}
	if p.IncludeTaskTags { q.Set("include_task_tags", "true") }
	if p.IncludeLocationNames { q.Set("include_location_names", "true") }
	if p.IncludeApprovalHistory { q.Set("include_approval_history", "true") }
	if p.IncludeApprovalDetails { q.Set("include_approval_details", "true") }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// Getsingulartimeentry — Get singular time entry
// GET /team/%s/time_entries/%s
func Getsingulartimeentry(ctx context.Context, client *api.Client, teamId string, timerId string, opts ...GetsingulartimeentryParams) (*clickupv2.GetsingulartimeentryJSONResponse, error) {
	var resp clickupv2.GetsingulartimeentryJSONResponse
	path := fmt.Sprintf("team/%s/time_entries/%s", teamId, timerId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GettimeentrieswithinadaterangeParams holds optional query parameters for Gettimeentrieswithinadaterange.
type GettimeentrieswithinadaterangeParams struct {
	StartDate float64 `url:"start_date,omitempty"`
	EndDate float64 `url:"end_date,omitempty"`
	Assignee float64 `url:"assignee,omitempty"`
	IncludeTaskTags bool `url:"include_task_tags,omitempty"`
	IncludeLocationNames bool `url:"include_location_names,omitempty"`
	IncludeApprovalHistory bool `url:"include_approval_history,omitempty"`
	IncludeApprovalDetails bool `url:"include_approval_details,omitempty"`
	SpaceId float64 `url:"space_id,omitempty"`
	FolderId float64 `url:"folder_id,omitempty"`
	ListId float64 `url:"list_id,omitempty"`
	TaskId string `url:"task_id,omitempty"`
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
	IsBillable bool `url:"is_billable,omitempty"`
}

func (p GettimeentrieswithinadaterangeParams) encode() string {
	q := url.Values{}
	if p.StartDate != 0 { q.Set("start_date", fmt.Sprintf("%g", p.StartDate)) }
	if p.EndDate != 0 { q.Set("end_date", fmt.Sprintf("%g", p.EndDate)) }
	if p.Assignee != 0 { q.Set("assignee", fmt.Sprintf("%g", p.Assignee)) }
	if p.IncludeTaskTags { q.Set("include_task_tags", "true") }
	if p.IncludeLocationNames { q.Set("include_location_names", "true") }
	if p.IncludeApprovalHistory { q.Set("include_approval_history", "true") }
	if p.IncludeApprovalDetails { q.Set("include_approval_details", "true") }
	if p.SpaceId != 0 { q.Set("space_id", fmt.Sprintf("%g", p.SpaceId)) }
	if p.FolderId != 0 { q.Set("folder_id", fmt.Sprintf("%g", p.FolderId)) }
	if p.ListId != 0 { q.Set("list_id", fmt.Sprintf("%g", p.ListId)) }
	if p.TaskId != "" { q.Set("task_id", p.TaskId) }
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if p.IsBillable { q.Set("is_billable", "true") }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// Gettimeentrieswithinadaterange — Get time entries within a date range
// GET /team/%s/time_entries
func Gettimeentrieswithinadaterange(ctx context.Context, client *api.Client, teamId string, opts ...GettimeentrieswithinadaterangeParams) (*clickupv2.GettimeentrieswithinadaterangeJSONResponse, error) {
	var resp clickupv2.GettimeentrieswithinadaterangeJSONResponse
	path := fmt.Sprintf("team/%s/time_entries", teamId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Gettimeentryhistory — Get time entry history
// GET /team/%s/time_entries/%s/history
func Gettimeentryhistory(ctx context.Context, client *api.Client, teamId string, timerId string) (*clickupv2.GettimeentryhistoryJSONResponse, error) {
	var resp clickupv2.GettimeentryhistoryJSONResponse
	path := fmt.Sprintf("team/%s/time_entries/%s/history", teamId, timerId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GettrackedtimeParams holds optional query parameters for Gettrackedtime.
type GettrackedtimeParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p GettrackedtimeParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// Gettrackedtime — Get tracked time
// GET /task/%s/time
func Gettrackedtime(ctx context.Context, client *api.Client, taskId string, opts ...GettrackedtimeParams) (*clickupv2.GettrackedtimeJSONResponse, error) {
	var resp clickupv2.GettrackedtimeJSONResponse
	path := fmt.Sprintf("task/%s/time", taskId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// InviteGuestToWorkspace — Invite Guest To Workspace
// POST /team/%s/guest
func InviteGuestToWorkspace(ctx context.Context, client *api.Client, teamId string, req *clickupv2.InviteGuestToWorkspaceJSONRequest) (*clickupv2.InviteGuestToWorkspaceJSONResponse, error) {
	var resp clickupv2.InviteGuestToWorkspaceJSONResponse
	path := fmt.Sprintf("team/%s/guest", teamId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// InviteUserToWorkspace — Invite User To Workspace
// POST /team/%s/user
func InviteUserToWorkspace(ctx context.Context, client *api.Client, teamId string, req *clickupv2.InviteUserToWorkspaceJSONRequest) (*clickupv2.InviteUserToWorkspaceJSONResponse, error) {
	var resp clickupv2.InviteUserToWorkspaceJSONResponse
	path := fmt.Sprintf("team/%s/user", teamId)
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// MergeTasks — Merge Tasks
// POST /task/%s/merge
func MergeTasks(ctx context.Context, client *api.Client, taskId string, req *clickupv2.MergeTasksJSONRequest) error {
	path := fmt.Sprintf("task/%s/merge", taskId)
	return do(ctx, client, "POST", path, req, nil)
}

// RemoveCustomFieldValueParams holds optional query parameters for RemoveCustomFieldValue.
type RemoveCustomFieldValueParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p RemoveCustomFieldValueParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// RemoveCustomFieldValue — Remove Custom Field Value
// DELETE /task/%s/field/%s
func RemoveCustomFieldValue(ctx context.Context, client *api.Client, taskId string, fieldId string, opts ...RemoveCustomFieldValueParams) (*clickupv2.RemoveCustomFieldValueJSONResponse, error) {
	var resp clickupv2.RemoveCustomFieldValueJSONResponse
	path := fmt.Sprintf("task/%s/field/%s", taskId, fieldId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RemoveGuestFromFolderParams holds optional query parameters for RemoveGuestFromFolder.
type RemoveGuestFromFolderParams struct {
	IncludeShared bool `url:"include_shared,omitempty"`
}

func (p RemoveGuestFromFolderParams) encode() string {
	q := url.Values{}
	if p.IncludeShared { q.Set("include_shared", "true") }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// RemoveGuestFromFolder — Remove Guest From Folder
// DELETE /folder/%s/guest/%s
func RemoveGuestFromFolder(ctx context.Context, client *api.Client, folderId string, guestId string, opts ...RemoveGuestFromFolderParams) (*clickupv2.RemoveGuestFromFolderJSONResponse, error) {
	var resp clickupv2.RemoveGuestFromFolderJSONResponse
	path := fmt.Sprintf("folder/%s/guest/%s", folderId, guestId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RemoveGuestFromListParams holds optional query parameters for RemoveGuestFromList.
type RemoveGuestFromListParams struct {
	IncludeShared bool `url:"include_shared,omitempty"`
}

func (p RemoveGuestFromListParams) encode() string {
	q := url.Values{}
	if p.IncludeShared { q.Set("include_shared", "true") }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// RemoveGuestFromList — Remove Guest From List
// DELETE /list/%s/guest/%s
func RemoveGuestFromList(ctx context.Context, client *api.Client, listId string, guestId string, opts ...RemoveGuestFromListParams) (*clickupv2.RemoveGuestFromListJSONResponse, error) {
	var resp clickupv2.RemoveGuestFromListJSONResponse
	path := fmt.Sprintf("list/%s/guest/%s", listId, guestId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RemoveGuestFromTaskParams holds optional query parameters for RemoveGuestFromTask.
type RemoveGuestFromTaskParams struct {
	IncludeShared bool `url:"include_shared,omitempty"`
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p RemoveGuestFromTaskParams) encode() string {
	q := url.Values{}
	if p.IncludeShared { q.Set("include_shared", "true") }
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// RemoveGuestFromTask — Remove Guest From Task
// DELETE /task/%s/guest/%s
func RemoveGuestFromTask(ctx context.Context, client *api.Client, taskId string, guestId string, opts ...RemoveGuestFromTaskParams) (*clickupv2.RemoveGuestFromTaskJSONResponse, error) {
	var resp clickupv2.RemoveGuestFromTaskJSONResponse
	path := fmt.Sprintf("task/%s/guest/%s", taskId, guestId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RemoveGuestFromWorkspace — Remove Guest From Workspace
// DELETE /team/%s/guest/%s
func RemoveGuestFromWorkspace(ctx context.Context, client *api.Client, teamId string, guestId string) (*clickupv2.RemoveGuestFromWorkspaceJSONResponse, error) {
	var resp clickupv2.RemoveGuestFromWorkspaceJSONResponse
	path := fmt.Sprintf("team/%s/guest/%s", teamId, guestId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RemoveTagFromTaskParams holds optional query parameters for RemoveTagFromTask.
type RemoveTagFromTaskParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p RemoveTagFromTaskParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// RemoveTagFromTask — Remove Tag From Task
// DELETE /task/%s/tag/%s
func RemoveTagFromTask(ctx context.Context, client *api.Client, taskId string, tagName string, opts ...RemoveTagFromTaskParams) (*clickupv2.RemoveTagFromTaskJSONResponse, error) {
	var resp clickupv2.RemoveTagFromTaskJSONResponse
	path := fmt.Sprintf("task/%s/tag/%s", taskId, tagName)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RemoveTaskFromList — Remove Task From List
// DELETE /list/%s/task/%s
func RemoveTaskFromList(ctx context.Context, client *api.Client, listId string, taskId string) (*clickupv2.RemoveTaskFromListJSONResponse, error) {
	var resp clickupv2.RemoveTaskFromListJSONResponse
	path := fmt.Sprintf("list/%s/task/%s", listId, taskId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RemoveUserFromWorkspace — Remove User From Workspace
// DELETE /team/%s/user/%s
func RemoveUserFromWorkspace(ctx context.Context, client *api.Client, teamId string, userId string) (*clickupv2.RemoveUserFromWorkspaceJSONResponse, error) {
	var resp clickupv2.RemoveUserFromWorkspaceJSONResponse
	path := fmt.Sprintf("team/%s/user/%s", teamId, userId)
	if err := do(ctx, client, "DELETE", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Removetagsfromtimeentries — Remove tags from time entries
// DELETE /team/%s/time_entries/tags
func Removetagsfromtimeentries(ctx context.Context, client *api.Client, teamId string, req *clickupv2.RemovetagsfromtimeentriesJSONRequest) (*clickupv2.RemovetagsfromtimeentriesJSONResponse, error) {
	var resp clickupv2.RemovetagsfromtimeentriesJSONResponse
	path := fmt.Sprintf("team/%s/time_entries/tags", teamId)
	if err := do(ctx, client, "DELETE", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SetCustomFieldValueParams holds optional query parameters for SetCustomFieldValue.
type SetCustomFieldValueParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p SetCustomFieldValueParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// SetCustomFieldValue — Set Custom Field Value
// POST /task/%s/field/%s
func SetCustomFieldValue(ctx context.Context, client *api.Client, taskId string, fieldId string, req *clickupv2.SetCustomFieldValueJSONRequest, opts ...SetCustomFieldValueParams) (*clickupv2.SetCustomFieldValueJSONResponse, error) {
	var resp clickupv2.SetCustomFieldValueJSONResponse
	path := fmt.Sprintf("task/%s/field/%s", taskId, fieldId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SharedHierarchy — Shared Hierarchy
// GET /team/%s/shared
func SharedHierarchy(ctx context.Context, client *api.Client, teamId string) (*clickupv2.SharedHierarchyJSONResponse, error) {
	var resp clickupv2.SharedHierarchyJSONResponse
	path := fmt.Sprintf("team/%s/shared", teamId)
	if err := do(ctx, client, "GET", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// StartatimeEntryParams holds optional query parameters for StartatimeEntry.
type StartatimeEntryParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p StartatimeEntryParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// StartatimeEntry — Start a time Entry
// POST /team/%s/time_entries/start
func StartatimeEntry(ctx context.Context, client *api.Client, teamId string, req *clickupv2.StartatimeEntryJSONRequest, opts ...StartatimeEntryParams) (*clickupv2.StartatimeEntryJSONResponse, error) {
	var resp clickupv2.StartatimeEntryJSONResponse
	path := fmt.Sprintf("team/%s/time_entries/start", teamId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// StopatimeEntry — Stop a time Entry
// POST /team/%s/time_entries/stop
func StopatimeEntry(ctx context.Context, client *api.Client, teamId string) (*clickupv2.StopatimeEntryJSONResponse, error) {
	var resp clickupv2.StopatimeEntryJSONResponse
	path := fmt.Sprintf("team/%s/time_entries/stop", teamId)
	if err := do(ctx, client, "POST", path, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// TracktimeParams holds optional query parameters for Tracktime.
type TracktimeParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p TracktimeParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// Tracktime — Track time
// POST /task/%s/time
func Tracktime(ctx context.Context, client *api.Client, taskId string, req *clickupv2.TracktimeJSONRequest, opts ...TracktimeParams) (*clickupv2.TracktimeJSONResponse, error) {
	var resp clickupv2.TracktimeJSONResponse
	path := fmt.Sprintf("task/%s/time", taskId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "POST", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateComment — Update Comment
// PUT /comment/%s
func UpdateComment(ctx context.Context, client *api.Client, commentId string, req *clickupv2.UpdateCommentJSONRequest) (*clickupv2.UpdateCommentJSONResponse, error) {
	var resp clickupv2.UpdateCommentJSONResponse
	path := fmt.Sprintf("comment/%s", commentId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateFolder — Update Folder
// PUT /folder/%s
func UpdateFolder(ctx context.Context, client *api.Client, folderId string, req *clickupv2.UpdateFolderJSONRequest) (*clickupv2.UpdateFolderJSONResponse, error) {
	var resp clickupv2.UpdateFolderJSONResponse
	path := fmt.Sprintf("folder/%s", folderId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateGoal — Update Goal
// PUT /goal/%s
func UpdateGoal(ctx context.Context, client *api.Client, goalId string, req *clickupv2.UpdateGoalJSONRequest) (*clickupv2.UpdateGoalJSONResponse, error) {
	var resp clickupv2.UpdateGoalJSONResponse
	path := fmt.Sprintf("goal/%s", goalId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateList — Update List
// PUT /list/%s
func UpdateList(ctx context.Context, client *api.Client, listId string, req *clickupv2.UpdateListJSONRequest) (*clickupv2.UpdateListJSONResponse, error) {
	var resp clickupv2.UpdateListJSONResponse
	path := fmt.Sprintf("list/%s", listId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateSpace — Update Space
// PUT /space/%s
func UpdateSpace(ctx context.Context, client *api.Client, spaceId string, req *clickupv2.UpdateSpaceJSONRequest) (*clickupv2.UpdateSpaceJSONResponse, error) {
	var resp clickupv2.UpdateSpaceJSONResponse
	path := fmt.Sprintf("space/%s", spaceId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateTaskParams holds optional query parameters for UpdateTask.
type UpdateTaskParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p UpdateTaskParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// UpdateTask — Update Task
// PUT /task/%s
func UpdateTask(ctx context.Context, client *api.Client, taskId string, req *clickupv2.UpdateTaskJSONRequest, opts ...UpdateTaskParams) (*clickupv2.UpdateTaskJSONResponse, error) {
	var resp clickupv2.UpdateTaskJSONResponse
	path := fmt.Sprintf("task/%s", taskId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateTeam — Update Group
// PUT /group/%s
func UpdateTeam(ctx context.Context, client *api.Client, groupId string, req *clickupv2.UpdateTeamJSONRequest) (*clickupv2.UpdateTeamJSONResponse, error) {
	var resp clickupv2.UpdateTeamJSONResponse
	path := fmt.Sprintf("group/%s", groupId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateView — Update View
// PUT /view/%s
func UpdateView(ctx context.Context, client *api.Client, viewId string, req *clickupv2.UpdateViewJSONRequest) (*clickupv2.UpdateViewJSONResponse, error) {
	var resp clickupv2.UpdateViewJSONResponse
	path := fmt.Sprintf("view/%s", viewId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateWebhook — Update Webhook
// PUT /webhook/%s
func UpdateWebhook(ctx context.Context, client *api.Client, webhookId string, req *clickupv2.UpdateWebhookJSONRequest) (*clickupv2.UpdateWebhookJSONResponse, error) {
	var resp clickupv2.UpdateWebhookJSONResponse
	path := fmt.Sprintf("webhook/%s", webhookId)
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// UpdateatimeEntryParams holds optional query parameters for UpdateatimeEntry.
type UpdateatimeEntryParams struct {
	CustomTaskIds bool `url:"custom_task_ids,omitempty"`
	TeamId float64 `url:"team_id,omitempty"`
}

func (p UpdateatimeEntryParams) encode() string {
	q := url.Values{}
	if p.CustomTaskIds { q.Set("custom_task_ids", "true") }
	if p.TeamId != 0 { q.Set("team_id", fmt.Sprintf("%g", p.TeamId)) }
	if len(q) == 0 { return "" }
	return "?" + q.Encode()
}

// UpdateatimeEntry — Update a time Entry
// PUT /team/%s/time_entries/%s
func UpdateatimeEntry(ctx context.Context, client *api.Client, teamId string, timerId string, req *clickupv2.UpdateatimeEntryJSONRequest, opts ...UpdateatimeEntryParams) (*clickupv2.UpdateatimeEntryJSONResponse, error) {
	var resp clickupv2.UpdateatimeEntryJSONResponse
	path := fmt.Sprintf("team/%s/time_entries/%s", teamId, timerId)
	if len(opts) > 0 { path += opts[0].encode() }
	if err := do(ctx, client, "PUT", path, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

