// Code generated by gen-api (fixrefs); DO NOT EDIT.
//
// Provides proper type definitions for self-referencing aliases that the
// oapi-codegen-exp cannot resolve, plus stubs for missing types.

package clickupv2

// DeleteV2TeamTeamIDTimeEntriesTagsRequest — resolved from spec $ref chain.
type DeleteV2TeamTeamIDTimeEntriesTagsRequest struct {
	Name string `json:"name"`
	TagBg string `json:"tag_bg"`
	TagFg string `json:"tag_fg"`
}

// GetV2FolderFolderIDField200Response — resolved from spec $ref chain.
type GetV2FolderFolderIDField200Response struct {
	DateCreated string `json:"date_created"`
	HideFromGuests bool `json:"hide_from_guests"`
	ID string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
	TypeConfig any `json:"type_config"`
}

// GetV2FolderFolderIDList200Response — resolved from spec $ref chain.
type GetV2FolderFolderIDList200Response struct {
	Archived bool `json:"archived"`
	Assignee any `json:"assignee"`
	Content string `json:"content"`
	DueDate any `json:"due_date"`
	Folder any `json:"folder"`
	ID string `json:"id"`
	Name string `json:"name"`
	Orderindex int `json:"orderindex"`
	OverrideStatuses bool `json:"override_statuses"`
	PermissionLevel string `json:"permission_level"`
	Priority any `json:"priority"`
	Space any `json:"space"`
	StartDate any `json:"start_date"`
	Status any `json:"status"`
	TaskCount any `json:"task_count"`
}

// GetV2ListListIDComment200Response — resolved from spec $ref chain.
type GetV2ListListIDComment200Response struct {
	AssignedBy any `json:"assigned_by"`
	Assignee any `json:"assignee"`
	Comment []any `json:"comment"`
	CommentText string `json:"comment_text"`
	Date string `json:"date"`
	ID string `json:"id"`
	Reactions []any `json:"reactions"`
	ReplyCount string `json:"reply_count"`
	Resolved bool `json:"resolved"`
	User any `json:"user"`
}

// GetV2ListListIDMember200Response — resolved from spec $ref chain.
type GetV2ListListIDMember200Response struct {
	Color any `json:"color"`
	Email string `json:"email"`
	ID int `json:"id"`
	Initials string `json:"initials"`
	ProfileInfo any `json:"profileInfo"`
	ProfilePicture string `json:"profilePicture"`
	Username string `json:"username"`
}

// GetV2SpaceSpaceID200Response — resolved from spec $ref chain.
type GetV2SpaceSpaceID200Response struct {
	Color string `json:"color"`
	ID string `json:"id"`
	Orderindex int `json:"orderindex"`
	Status string `json:"status"`
	Type string `json:"type"`
}

// GetV2SpaceSpaceIDField200Response — resolved from spec $ref chain.
type GetV2SpaceSpaceIDField200Response struct {
	DateCreated string `json:"date_created"`
	HideFromGuests bool `json:"hide_from_guests"`
	ID string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
	TypeConfig any `json:"type_config"`
}

// GetV2SpaceSpaceIDTag200Response — resolved from spec $ref chain.
type GetV2SpaceSpaceIDTag200Response struct {
	Name string `json:"name"`
	TagBg string `json:"tag_bg"`
	TagFg string `json:"tag_fg"`
}

// GetV2TeamTeamIDField200Response — resolved from spec $ref chain.
type GetV2TeamTeamIDField200Response struct {
	DateCreated string `json:"date_created"`
	HideFromGuests bool `json:"hide_from_guests"`
	ID string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
	TypeConfig any `json:"type_config"`
}

// GetV2TeamTeamIDWebhook200Response — resolved from spec $ref chain.
type GetV2TeamTeamIDWebhook200Response struct {
	ClientID string `json:"client_id"`
	Endpoint string `json:"endpoint"`
	Events []any `json:"events"`
	FolderID any `json:"folder_id"`
	Health any `json:"health"`
	ID string `json:"id"`
	ListID any `json:"list_id"`
	Secret string `json:"secret"`
	SpaceID any `json:"space_id"`
	TaskID any `json:"task_id"`
	TeamID int `json:"team_id"`
	Userid int `json:"userid"`
}

// PostV2TeamTeamIDTimeEntries200Response — resolved from spec $ref chain.
type PostV2TeamTeamIDTimeEntries200Response struct {
	Name string `json:"name"`
	TagBg string `json:"tag_bg"`
	TagFg string `json:"tag_fg"`
}

// PostV2TeamTeamIDTimeEntriesTagsRequest — resolved from spec $ref chain.
type PostV2TeamTeamIDTimeEntriesTagsRequest struct {
	Name string `json:"name"`
	TagBg string `json:"tag_bg"`
	TagFg string `json:"tag_fg"`
}

// PutV2SpaceSpaceID200Response — resolved from spec $ref chain.
type PutV2SpaceSpaceID200Response struct {
	Color string `json:"color"`
	ID string `json:"id"`
	Orderindex int `json:"orderindex"`
	Status string `json:"status"`
	Type string `json:"type"`
}

// PutV2TeamTeamIDTimeEntriesTimerIDRequest — resolved from spec $ref chain.
type PutV2TeamTeamIDTimeEntriesTimerIDRequest struct {
	Name string `json:"name"`
}

// GetV2FolderFolderIDView200Response — codegen could not resolve; using any.
type GetV2FolderFolderIDView200Response = any

// GetV2ListListIDView200Response — codegen could not resolve; using any.
type GetV2ListListIDView200Response = any

// GetV2SpaceSpaceIDView200Response — codegen could not resolve; using any.
type GetV2SpaceSpaceIDView200Response = any

// GetV2TeamTeamIDView200Response — codegen could not resolve; using any.
type GetV2TeamTeamIDView200Response = any

// PostV2FolderFolderIDList200Response — codegen could not resolve; using any.
type PostV2FolderFolderIDList200Response = any

// PutV2ListListID200Response — codegen could not resolve; using any.
type PutV2ListListID200Response = any

// GetV2Group200Response — referenced but not defined by codegen.
type GetV2Group200Response = any

// GetV2ListListID200Response — referenced but not defined by codegen.
type GetV2ListListID200Response = any

// GetV2ListListIDTask200Response — referenced but not defined by codegen.
type GetV2ListListIDTask200Response = any

// GetV2TaskBulkTimeInStatusTaskIds200Response — referenced but not defined by codegen.
type GetV2TaskBulkTimeInStatusTaskIds200Response = any

// GetV2TaskTaskID200Response — referenced but not defined by codegen.
type GetV2TaskTaskID200Response = any

// GetV2TeamTeamIDGoal200Response — referenced but not defined by codegen.
type GetV2TeamTeamIDGoal200Response = any

// GetV2TeamTeamIDSpace200Response — referenced but not defined by codegen.
type GetV2TeamTeamIDSpace200Response = any

// GetV2TeamTeamIDTask200Response — referenced but not defined by codegen.
type GetV2TeamTeamIDTask200Response = any

// GetV2TeamTeamIDTimeEntries200Response — referenced but not defined by codegen.
type GetV2TeamTeamIDTimeEntries200Response = any

// GetV2ViewViewIDComment200Response — referenced but not defined by codegen.
type GetV2ViewViewIDComment200Response = any

// GetV2ViewViewIDTask200Response — referenced but not defined by codegen.
type GetV2ViewViewIDTask200Response = any

// PostV2FolderFolderIDGuestGuestID200Response — referenced but not defined by codegen.
type PostV2FolderFolderIDGuestGuestID200Response = any

// PostV2GoalGoalIDKeyResult200Response — referenced but not defined by codegen.
type PostV2GoalGoalIDKeyResult200Response = any

// PostV2ListListIDGuestGuestID200Response — referenced but not defined by codegen.
type PostV2ListListIDGuestGuestID200Response = any

// PostV2ListListIDTask200Response — referenced but not defined by codegen.
type PostV2ListListIDTask200Response = any

// PostV2SpaceSpaceIDList200Response — referenced but not defined by codegen.
type PostV2SpaceSpaceIDList200Response = any

// PostV2TeamTeamIDGuest200Response — referenced but not defined by codegen.
type PostV2TeamTeamIDGuest200Response = any

// PutV2KeyResultKeyResultID200Response — referenced but not defined by codegen.
type PutV2KeyResultKeyResultID200Response = any

// PutV2TaskTaskID200Response — referenced but not defined by codegen.
type PutV2TaskTaskID200Response = any

